window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['qatar22']={
  key:'qatar22',name:'FIFA World Cup',fullName:'2022 FIFA World Cup',
  year:2022,host:'Qatar',startDate:'2022-11-21',endDate:'2022-12-18',
  tagline:"The winter World Cup. Bellingham arrives. Quarter-final exit to France.",
  qualifyingRequired:true,qualifierGroup:'WCQ_2022_I',format:'world_cup_32',
  colours:{primary:'#8B1A4A',secondary:'#C8C8C8',accent:'#FFFFFF',text:'#fff',bg:'#0A000A',bgCard:'#1A001A'},
  atmosphere:{context:"The first winter World Cup in gleaming Qatar stadiums. Bellingham is the breakthrough star. Kane and Saka lead a talented squad. Can England finally deliver on their potential?",pressureLevel:'high',mediaExpectation:'Semi-finals at minimum.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'Qatar',flag:'🇶🇦',rating:67}, {name:'Ecuador',flag:'🇪🇨',rating:73}, {name:'Senegal',flag:'🇸🇳',rating:77}, {name:'Netherlands',flag:'🇳🇱',rating:83}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'England',flag:'🏴U000e0067U000e0062U000e0065U000e006eU000e0067U000e007f',rating:85}, {name:'USA',flag:'🇺🇸',rating:76}, {name:'Wales',flag:'🏴U000e0067U000e0062U000e0077U000e006cU000e0073U000e007f',rating:74}, {name:'Iran',flag:'🇮🇷',rating:69}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'Argentina',flag:'🇦🇷',rating:88}, {name:'Saudi Arabia',flag:'🇸🇦',rating:70}, {name:'Mexico',flag:'🇲🇽',rating:76}, {name:'Poland',flag:'🇵🇱',rating:76}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'France',flag:'🇫🇷',rating:89}, {name:'Australia',flag:'🇦🇺',rating:73}, {name:'Denmark',flag:'🇩🇰',rating:78}, {name:'Tunisia',flag:'🇹🇳',rating:69}]},
  {id:'E',name:'Group E',qualified:2,teams:[{name:'Spain',flag:'🇪🇸',rating:85}, {name:'Costa Rica',flag:'🇨🇷',rating:70}, {name:'Germany',flag:'🇩🇪',rating:83}, {name:'Japan',flag:'🇯🇵',rating:75}]},
  {id:'F',name:'Group F',qualified:2,teams:[{name:'Belgium',flag:'🇧🇪',rating:82}, {name:'Canada',flag:'🇨🇦',rating:72}, {name:'Morocco',flag:'🇲🇦',rating:79}, {name:'Croatia',flag:'🇭🇷',rating:81}]},
  {id:'G',name:'Group G',qualified:2,teams:[{name:'Brazil',flag:'🇧🇷',rating:87}, {name:'Serbia',flag:'🇷🇸',rating:76}, {name:'Switzerland',flag:'🇨🇭',rating:77}, {name:'Cameroon',flag:'🇨🇲',rating:72}]},
  {id:'H',name:'Group H',qualified:2,teams:[{name:'Portugal',flag:'🇵🇹',rating:84}, {name:'Ghana',flag:'🇬🇭',rating:70}, {name:'Uruguay',flag:'🇺🇾',rating:79}, {name:'South Korea',flag:'🇰🇷',rating:74}]},
],
  teams:{
    England:{rating:85,manager:'Gareth Southgate',style:'balanced'},France:{rating:89,manager:'Didier Deschamps',style:'attacking'},
    Brazil:{rating:87,manager:'Tite',style:'attacking'},Argentina:{rating:88,manager:'Lionel Scaloni',style:'attacking'},
    Spain:{rating:85,manager:'Luis Enrique',style:'attacking'},Netherlands:{rating:83,manager:'Louis van Gaal',style:'defensive'},
    Portugal:{rating:84,manager:'Fernando Santos',style:'balanced'},Croatia:{rating:81,manager:'Zlatko Dalic',style:'balanced'},
    Germany:{rating:83,manager:'Hansi Flick',style:'attacking'},Belgium:{rating:82,manager:'Roberto Martinez',style:'attacking'},
    Uruguay:{rating:79,manager:'Diego Alonso',style:'defensive'},USA:{rating:76,manager:'Gregg Berhalter',style:'balanced'},
    Morocco:{rating:79,manager:'Walid Regragui',style:'defensive'},Switzerland:{rating:77,manager:'Murat Yakin',style:'balanced'},
    Senegal:{rating:77,manager:'Aliou Cisse',style:'balanced'},Australia:{rating:73,manager:'Graham Arnold',style:'balanced'},
    Poland:{rating:76,manager:'Czeslaw Michniewicz',style:'defensive'},Japan:{rating:75,manager:'Hajime Moriyasu',style:'balanced'},
    Mexico:{rating:76,manager:'Gerardo Martino',style:'balanced'},Denmark:{rating:78,manager:'Kasper Hjulmand',style:'balanced'},
    Cameroon:{rating:72,manager:'Rigobert Song',style:'balanced'},Ghana:{rating:70,manager:'Otto Addo',style:'balanced'},
    'Saudi Arabia':{rating:70,manager:'Herve Renard',style:'defensive'},Iran:{rating:69,manager:'Carlos Queiroz',style:'defensive'},
    Wales:{rating:74,manager:'Robert Page',style:'defensive'},'South Korea':{rating:74,manager:'Paulo Bento',style:'balanced'},
    'Costa Rica':{rating:70,manager:'Luis Fernando Suarez',style:'defensive'},Serbia:{rating:76,manager:'Dragan Stojkovic',style:'balanced'},
    Ecuador:{rating:73,manager:'Gustavo Alfaro',style:'balanced'},Tunisia:{rating:69,manager:'Jalel Kadri',style:'defensive'},
    Canada:{rating:72,manager:'John Herdman',style:'balanced'},Qatar:{rating:67,manager:'Felix Sanchez',style:'defensive'},
  },
  allFixtures:[
    {id:'q22_G1',home:'England',away:'Iran',group:'B',stage:'group',date:'2022-11-21',neutral:true,historicResult:{home:6,away:2}},
    {id:'q22_G2',home:'USA',away:'Wales',group:'B',stage:'group',date:'2022-11-21',neutral:true,historicResult:{home:1,away:1}},
    {id:'q22_G3',home:'England',away:'USA',group:'B',stage:'group',date:'2022-11-25',neutral:true,historicResult:{home:0,away:0}},
    {id:'q22_G4',home:'Iran',away:'Wales',group:'B',stage:'group',date:'2022-11-25',neutral:true,historicResult:{home:0,away:2}},
    {id:'q22_G5',home:'England',away:'Wales',group:'B',stage:'group',date:'2022-11-29',neutral:true,historicResult:{home:3,away:0}},
    {id:'q22_G6',home:'Iran',away:'USA',group:'B',stage:'group',date:'2022-11-29',neutral:true,historicResult:{home:0,away:1}},
    {id:'q22_R1',home:'B_1',away:'A_2',stage:'r16',date:'2022-12-04',neutral:true},
    {id:'q22_R2',home:'A_1',away:'B_2',stage:'r16',date:'2022-12-04',neutral:true},
    {id:'q22_QF1',home:'q22_R1_W',away:'q22_R5_W',stage:'qf',date:'2022-12-10',neutral:true},
    {id:'q22_SF1',home:'q22_QF1_W',away:'q22_QF2_W',stage:'sf',date:'2022-12-14',neutral:true},
    {id:'q22_3P',home:'q22_SF1_L',away:'q22_SF2_L',stage:'3rd',date:'2022-12-17',neutral:true},
    {id:'q22_F',home:'q22_SF1_W',away:'q22_SF2_W',stage:'final',date:'2022-12-18',neutral:true},
  ],
  knockoutStructure:{r16:[{fixtureId:'q22_R1'},{fixtureId:'q22_R2'}],qf:[{fixtureId:'q22_QF1'}],sf:[{fixtureId:'q22_SF1'}],final:{fixtureId:'q22_F'}},
  squads:{
    England:['Harry Kane','Bukayo Saka','Raheem Sterling','Phil Foden','Jude Bellingham','Jordan Henderson','Declan Rice','Kyle Walker','Kieran Trippier','Harry Maguire','John Stones','Jordan Pickford','Marcus Rashford','Jack Grealish','Mason Mount','Kalvin Phillips','Eric Dier','Luke Shaw','Ben White','Nick Pope','Aaron Ramsdale','Conor Gallagher','Mason Greenwood'],
    France:["Kylian Mbappe","Antoine Griezmann","Olivier Giroud","Theo Hernandez","Raphael Varane","Dayot Upamecano","Hugo Lloris"],
    Argentina:["Lionel Messi","Julian Alvarez","Angel Di Maria","Enzo Fernandez","Emiliano Martinez"],
    Morocco:["Achraf Hakimi","Youssef En-Nesyri","Hakim Ziyech","Romain Saiss","Yassine Bounou"],
  },
  commentary:{context:["Winter World Cup. Bellingham the star. Saka and Kane dangerous."],groupStage:["Iran are beatable — big win please.","USA: must not slip up."],goodResult:["Bellingham looks world class."],badResult:["Southgate's caution cost us again."]},
  historicalNotes:{groupResult:'Won Group B — beat Iran 6-2, drew USA 0-0, beat Wales 3-0',knockoutRun:'Beat Senegal 3-0, lost to France 1-2 in quarter-final',topScorer:'Harry Kane 3 goals',keyMoment:'Bellingham header vs Iran. Stunning Kane miss vs France.'},
};