window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['usa94']={
  key:'usa94',name:'FIFA World Cup',fullName:'1994 FIFA World Cup',
  year:1994,host:'United States',startDate:'1994-06-17',endDate:'1994-07-17',
  tagline:"England didn't qualify. Graham Taylor's reign ends in disaster.",
  qualifyingRequired:true,qualifierGroup:'WCQ_1994_2',format:'world_cup_24',
  colours:{primary:'#B22234',secondary:'#3C3B6E',accent:'#FFFFFF',text:'#fff',bg:'#0A000A',bgCard:'#15000A'},
  atmosphere:{context:"England FAILED TO QUALIFY. Graham Taylor resigned. The Do I Not Like That era. If you're playing this tournament, you've changed history.",pressureLevel:'extreme',mediaExpectation:'Qualify first. Then show up.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'Romania',flag:'🇷🇴',rating:79}, {name:'Switzerland',flag:'🇨🇭',rating:73}, {name:'USA',flag:'🇺🇸',rating:72}, {name:'Colombia',flag:'🇨🇴',rating:78}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'England',flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿',rating:81}, {name:'Republic of Ireland',flag:'🇮🇪',rating:74}, {name:'Italy',flag:'🇮🇹',rating:85}, {name:'Norway',flag:'🇳🇴',rating:72}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'Germany',flag:'🇩🇪',rating:87}, {name:'Bolivia',flag:'🇧🇴',rating:65}, {name:'Spain',flag:'🇪🇸',rating:81}, {name:'South Korea',flag:'🇰🇷',rating:69}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'Argentina',flag:'🇦🇷',rating:86}, {name:'Greece',flag:'🇬🇷',rating:65}, {name:'Nigeria',flag:'🇳🇬',rating:77}, {name:'Bulgaria',flag:'🇧🇬',rating:78}]},
  {id:'E',name:'Group E',qualified:2,teams:[{name:'Mexico',flag:'🇲🇽',rating:76}, {name:'Ireland',flag:'🇮🇪',rating:72}, {name:'Italy',flag:'🇮🇹',rating:85}, {name:'Norway',flag:'🇳🇴',rating:72}]},
  {id:'F',name:'Group F',qualified:2,teams:[{name:'Belgium',flag:'🇧🇪',rating:76}, {name:'Morocco',flag:'🇲🇦',rating:69}, {name:'Netherlands',flag:'🇳🇱',rating:84}, {name:'Saudi Arabia',flag:'🇸🇦',rating:72}]}
],
  teams:{
    England:{rating:81,manager:'Terry Venables',style:'balanced'},Brazil:{rating:89,manager:'Carlos Alberto Parreira',style:'attacking'},
    Italy:{rating:85,manager:'Arrigo Sacchi',style:'defensive'},Germany:{rating:87,manager:'Berti Vogts',style:'balanced'},
    Argentina:{rating:86,manager:'Alfio Basile',style:'attacking'},Netherlands:{rating:84,manager:'Dick Advocaat',style:'attacking'},
    Sweden:{rating:82,manager:'Tommy Soderberg',style:'defensive'},Bulgaria:{rating:78,manager:'Dimitar Penev',style:'balanced'},
    Romania:{rating:79,manager:'Anghel Iordanescu',style:'attacking'},Spain:{rating:81,manager:'Javier Clemente',style:'attacking'},
    Nigeria:{rating:77,manager:'Clemens Westerhof',style:'balanced'},Mexico:{rating:76,manager:'Miguel Mejia Baron',style:'balanced'},
    USA:{rating:72,manager:'Bora Milutinovic',style:'defensive'},'Republic of Ireland':{rating:74,manager:'Jack Charlton',style:'defensive'},
    Belgium:{rating:76,manager:'Paul Van Himst',style:'balanced'},'Saudi Arabia':{rating:72,manager:'Jorge Solari',style:'balanced'},
    Switzerland:{rating:73,manager:'Roy Hodgson',style:'defensive'},Colombia:{rating:78,manager:'Francisco Maturana',style:'attacking'},
    'South Korea':{rating:69,manager:'Kim Ho',style:'defensive'},Morocco:{rating:69,manager:'Abdelmajid Dolmy',style:'defensive'},
    Bolivia:{rating:65,manager:'Xabier Azkargorta',style:'defensive'},Greece:{rating:65,manager:'Alketas Panagoulias',style:'defensive'},
    Norway:{rating:72,manager:'Egil Olsen',style:'defensive'},
  },
  allFixtures:[
    {id:'u94_G1',home:'England',away:'Republic of Ireland',group:'B',stage:'group',date:'1994-06-24',neutral:true},
    {id:'u94_G2',home:'Italy',away:'Norway',group:'B',stage:'group',date:'1994-06-23',neutral:true,historicResult:{home:1,away:0}},
    {id:'u94_G3',home:'England',away:'Norway',group:'B',stage:'group',date:'1994-06-28',neutral:true},
    {id:'u94_G4',home:'Italy',away:'Republic of Ireland',group:'B',stage:'group',date:'1994-06-28',neutral:true,historicResult:{home:1,away:0}},
    {id:'u94_G5',home:'England',away:'Italy',group:'B',stage:'group',date:'1994-07-04',neutral:true},
    {id:'u94_G6',home:'Republic of Ireland',away:'Norway',group:'B',stage:'group',date:'1994-07-04',neutral:true,historicResult:{home:0,away:0}},
    {id:'u94_R1',home:'B_1',away:'A_3_or_D_3',stage:'r16',date:'1994-07-05',neutral:true},
    {id:'u94_QF1',home:'u94_R1_W',away:'u94_R2_W',stage:'qf',date:'1994-07-09',neutral:true},
    {id:'u94_SF1',home:'u94_QF1_W',away:'u94_QF2_W',stage:'sf',date:'1994-07-13',neutral:true},
    {id:'u94_3P',home:'u94_SF1_L',away:'u94_SF2_L',stage:'3rd',date:'1994-07-16',neutral:true},
    {id:'u94_F',home:'u94_SF1_W',away:'u94_SF2_W',stage:'final',date:'1994-07-17',neutral:true},
  ],
  knockoutStructure:{r16:[{fixtureId:'u94_R1'}],qf:[{fixtureId:'u94_QF1'}],sf:[{fixtureId:'u94_SF1'}],final:{fixtureId:'u94_F'}},
  squads:{
    England:['Alan Shearer','Les Ferdinand','Teddy Sheringham','Peter Beardsley','David Platt','Paul Ince','Paul Gascoigne','David Batty','Tony Adams','Des Walker','Stuart Pearce','David Seaman','Tim Flowers','Ian Walker','Gareth Southgate','Steve Howey','Phil Neville','Gary Neville','John Barnes','Andy Cole','Robbie Fowler'],
    Brazil:["Romario","Bebeto","Mazinho","Mauro Silva","Aldair","Taffarel"],
    Italy:["Roberto Baggio","Dino Baggio","Costacurta","Baresi","Maldini","Pagliuca"],
    Germany:["Jurgen Klinsmann","Karl-Heinz Riedle","Lothar Matthaus","Andreas Moller"],
  },
  commentary:{context:["England DIDN'T qualify historically. You've changed that. Ireland and Italy await."],groupStage:["Ireland first — must not lose.","Italy are strong — shut them out and nick one."],goodResult:["Shearer is a monster."],badResult:["The Gascoigne problem. Can't get him fit."]},
  historicalNotes:{groupResult:'England did not qualify historically — Taylor era failure',knockoutRun:'Alternate history only',topScorer:'Romario & Bebeto for Brazil',keyMoment:"Ronald Koeman should have been sent off. Taylor loses the plot. Do I not like that."},
};