window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['korea02']={
  key:'korea02',name:'FIFA World Cup',fullName:'2002 FIFA World Cup',
  year:2002,host:'South Korea & Japan',startDate:'2002-05-31',endDate:'2002-06-30',
  tagline:"Owen vs Argentina. Beckham's redemption. Quarter-final exit to Brazil.",
  qualifyingRequired:true,qualifierGroup:'WCQ_2002_9',format:'world_cup_32',
  colours:{primary:'#C60C30',secondary:'#003478',accent:'#FFFFFF',text:'#fff',bg:'#0A0010',bgCard:'#100020'},
  atmosphere:{context:"Sven's England. Beckham's redemption — he scores the penalty vs Argentina. Owen destroys them. But Ronaldinho lobs Seaman. Quarter-final exit.",pressureLevel:'high',mediaExpectation:'Semi-finals. Beckham is back. Owen is electric.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'Denmark',flag:'🇩🇰',rating:77}, {name:'Senegal',flag:'🇸🇳',rating:74}, {name:'Uruguay',flag:'🇺🇾',rating:75}, {name:'France',flag:'🇫🇷',rating:86}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'Spain',flag:'🇪🇸',rating:83}, {name:'Paraguay',flag:'🇵🇾',rating:73}, {name:'South Africa',flag:'🇿🇦',rating:68}, {name:'Slovenia',flag:'🇸🇮',rating:67}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'Brazil',flag:'🇧🇷',rating:90}, {name:'Turkey',flag:'🇹🇷',rating:80}, {name:'China',flag:'🇨🇳',rating:65}, {name:'Costa Rica',flag:'🇨🇷',rating:69}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'South Korea',flag:'🇰🇷',rating:76}, {name:'USA',flag:'🇺🇸',rating:76}, {name:'Portugal',flag:'🇵🇹',rating:81}, {name:'Poland',flag:'🇵🇱',rating:71}]},
  {id:'E',name:'Group E',qualified:2,teams:[{name:'Germany',flag:'🇩🇪',rating:84}, {name:'Ireland',flag:'🇮🇪',rating:73}, {name:'Cameroon',flag:'🇨🇲',rating:73}, {name:'Saudi Arabia',flag:'🇸🇦',rating:68}]},
  {id:'F',name:'Group F',qualified:2,teams:[{name:'England',flag:'🏴U000e0067U000e0062U000e0065U000e006eU000e0067U000e007f',rating:82}, {name:'Sweden',flag:'🇸🇪',rating:79}, {name:'Argentina',flag:'🇦🇷',rating:85}, {name:'Nigeria',flag:'🇳🇬',rating:73}]},
  {id:'G',name:'Group G',qualified:2,teams:[{name:'Mexico',flag:'🇲🇽',rating:78}, {name:'Croatia',flag:'🇭🇷',rating:75}, {name:'Ecuador',flag:'🇪🇨',rating:70}, {name:'Italy',flag:'🇮🇹',rating:83}]},
  {id:'H',name:'Group H',qualified:2,teams:[{name:'Japan',flag:'🇯🇵',rating:73}, {name:'Belgium',flag:'🇧🇪',rating:75}, {name:'Russia',flag:'🇷🇺',rating:72}, {name:'Tunisia',flag:'🇹🇳',rating:67}]},
],
  teams:{
    England:{rating:82,manager:'Sven-Goran Eriksson',style:'attacking'},Brazil:{rating:90,manager:'Luiz Felipe Scolari',style:'attacking'},
    Germany:{rating:84,manager:'Rudi Voller',style:'balanced'},Turkey:{rating:80,manager:'Senol Gunes',style:'balanced'},
    'South Korea':{rating:76,manager:'Guus Hiddink',style:'balanced'},Spain:{rating:83,manager:'Jose Antonio Camacho',style:'attacking'},
    USA:{rating:76,manager:'Bruce Arena',style:'balanced'},Senegal:{rating:74,manager:'Bruno Metsu',style:'balanced'},
    Mexico:{rating:78,manager:'Javier Aguirre',style:'balanced'},Denmark:{rating:77,manager:'Morten Olsen',style:'balanced'},
    Japan:{rating:73,manager:'Philippe Troussier',style:'balanced'},Sweden:{rating:79,manager:'Tommy Soderberg',style:'balanced'},
    Argentina:{rating:85,manager:'Marcelo Bielsa',style:'attacking'},Portugal:{rating:81,manager:'Antonio Oliveira',style:'attacking'},
    Italy:{rating:83,manager:'Giovanni Trapattoni',style:'defensive'},Paraguay:{rating:73,manager:'Cesare Maldini',style:'defensive'},
    France:{rating:86,manager:'Roger Lemerre',style:'attacking'},Belgium:{rating:75,manager:'Robert Waseige',style:'defensive'},
    Ireland:{rating:73,manager:'Mick McCarthy',style:'defensive'},Russia:{rating:72,manager:'Oleg Romantsev',style:'balanced'},
    Nigeria:{rating:73,manager:'Festus Onigbinde',style:'balanced'},Croatia:{rating:75,manager:'Mirko Jozic',style:'balanced'},
    Ecuador:{rating:70,manager:'Hernan Dario Gomez',style:'balanced'},Uruguay:{rating:75,manager:'Victor Pua',style:'balanced'},
    Cameroon:{rating:73,manager:'Winfried Schafer',style:'balanced'},'South Africa':{rating:68,manager:'Carlos Alberto Parreira',style:'balanced'},
    'Saudi Arabia':{rating:68,manager:'Nasser Al-Johar',style:'balanced'},Poland:{rating:71,manager:'Jerzy Engel',style:'balanced'},
    China:{rating:65,manager:'Bora Milutinovic',style:'balanced'},'Costa Rica':{rating:69,manager:'Alexandre Guimaraes',style:'defensive'},
    Tunisia:{rating:67,manager:'Henryk Kasperczak',style:'defensive'},Slovenia:{rating:67,manager:'Srecko Katanec',style:'defensive'},
  },
  allFixtures:[
    {id:'k02_G1',home:'England',away:'Sweden',group:'F',stage:'group',date:'2002-06-02',neutral:true,historicResult:{home:1,away:1}},
    {id:'k02_G2',home:'Nigeria',away:'Argentina',group:'F',stage:'group',date:'2002-06-02',neutral:true,historicResult:{home:1,away:1}},
    {id:'k02_G3',home:'England',away:'Argentina',group:'F',stage:'group',date:'2002-06-07',neutral:true,historicResult:{home:1,away:0}},
    {id:'k02_G4',home:'Nigeria',away:'Sweden',group:'F',stage:'group',date:'2002-06-07',neutral:true,historicResult:{home:0,away:2}},
    {id:'k02_G5',home:'England',away:'Nigeria',group:'F',stage:'group',date:'2002-06-12',neutral:true,historicResult:{home:0,away:0}},
    {id:'k02_G6',home:'Sweden',away:'Argentina',group:'F',stage:'group',date:'2002-06-12',neutral:true,historicResult:{home:1,away:1}},
    {id:'k02_R1',home:'F_1',away:'E_2',stage:'r16',date:'2002-06-15',neutral:true},
    {id:'k02_QF1',home:'k02_R1_W',away:'k02_R2_W',stage:'qf',date:'2002-06-21',neutral:true},
    {id:'k02_SF1',home:'k02_QF1_W',away:'k02_QF2_W',stage:'sf',date:'2002-06-26',neutral:true},
    {id:'k02_3P',home:'k02_SF1_L',away:'k02_SF2_L',stage:'3rd',date:'2002-06-29',neutral:true},
    {id:'k02_F',home:'k02_SF1_W',away:'k02_SF2_W',stage:'final',date:'2002-06-30',neutral:true},
  ],
  knockoutStructure:{r16:[{fixtureId:'k02_R1'}],qf:[{fixtureId:'k02_QF1'}],sf:[{fixtureId:'k02_SF1'}],final:{fixtureId:'k02_F'}},
  squads:{
    England:['Michael Owen','David Beckham','Emile Heskey','Paul Scholes','Nicky Butt','Steven Gerrard','Paul Ince','Rio Ferdinand','Ashley Cole','Gary Neville','Sol Campbell','David Seaman','Nigel Martyn','David James','Robbie Fowler','Andy Cole','Teddy Sheringham','Kieron Dyer','Owen Hargreaves','Gareth Barry','Wes Brown','Wayne Bridge'],
    Brazil:["Ronaldo","Ronaldinho","Rivaldo","Roberto Carlos","Cafu","Lucio"],
    Germany:["Michael Ballack","Oliver Kahn","Miroslav Klose","Bernd Schneider"],
    Turkey:["Hakan Sukur","Ilhan Mansiz","Emre Belozoglu","Rustu Recber"],
  },
  commentary:{context:["Sven's England. Beckham returns. Owen is dangerous."],groupStage:["Sweden — solid start required.","Argentina — the big one. Beckham's revenge."],goodResult:["Beckham the penalty. Owen the destroyer."],badResult:["We're too cautious without the ball."]},
  historicalNotes:{groupResult:'1st in Group F — drew Sweden 1-1, beat Argentina 1-0, drew Nigeria 0-0',knockoutRun:'Beat Denmark 3-0, lost to Brazil 1-2 (Ronaldinho free kick)',topScorer:'Michael Owen 2 goals',keyMoment:"Beckham's penalty vs Argentina. Ronaldinho's free kick lobbing Seaman."},
};