window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['euro2000']={
  key:'euro2000',name:'UEFA European Championship',fullName:'UEFA Euro 2000',
  year:2000,host:'Belgium & Netherlands',startDate:'2000-06-10',endDate:'2000-07-02',
  tagline:"Keegan's England lose to Romania. Figo's Portugal crush them. Another painful exit.",
  qualifyingRequired:true,qualifierGroup:'ECQ_EURO2000_5',format:'euros_16',
  colours:{primary:'#EF3340',secondary:'#000000',accent:'#FAE042',text:'#fff',bg:'#0A0000',bgCard:'#150000'},
  atmosphere:{context:"Kevin Keegan's England. Shearer on the way out. Owen the main hope. Romania humiliate them with a last-minute winner. Out in the group stage.",pressureLevel:'high',mediaExpectation:'Quarters.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'Portugal',flag:'🇵🇹',rating:84}, {name:'Romania',flag:'🇷🇴',rating:77}, {name:'England',flag:'🏴U000e0067U000e0062U000e0065U000e006eU000e0067U000e007f',rating:80}, {name:'Germany',flag:'🇩🇪',rating:81}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'Spain',flag:'🇪🇸',rating:82}, {name:'Norway',flag:'🇳🇴',rating:72}, {name:'Yugoslavia',flag:'🇷🇸',rating:78}, {name:'Slovenia',flag:'🇸🇮',rating:67}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'Italy',flag:'🇮🇹',rating:85}, {name:'Turkey',flag:'🇹🇷',rating:76}, {name:'Belgium',flag:'🇧🇪',rating:73}, {name:'Sweden',flag:'🇸🇪',rating:75}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'Netherlands',flag:'🇳🇱',rating:87}, {name:'Czech Republic',flag:'🇨🇿',rating:76}, {name:'Denmark',flag:'🇩🇰',rating:75}, {name:'France',flag:'🇫🇷',rating:89}]},
],
  teams:{
    England:{rating:80,manager:'Kevin Keegan',style:'attacking'},France:{rating:89,manager:'Roger Lemerre',style:'attacking'},
    Netherlands:{rating:87,manager:'Frank Rijkaard',style:'attacking'},Italy:{rating:85,manager:'Dino Zoff',style:'defensive'},
    Portugal:{rating:84,manager:'Humberto Coelho',style:'attacking'},Spain:{rating:82,manager:'Jose Antonio Camacho',style:'attacking'},
    Romania:{rating:77,manager:'Emerich Jenei',style:'balanced'},'Czech Republic':{rating:76,manager:'Ivan Hasek',style:'balanced'},
    Germany:{rating:81,manager:'Erich Ribbeck',style:'balanced'},Yugoslavia:{rating:78,manager:'Vujadin Boskov',style:'balanced'},
    Turkey:{rating:76,manager:'Mustafa Denizli',style:'balanced'},Denmark:{rating:75,manager:'Bo Johansson',style:'defensive'},
    Sweden:{rating:75,manager:'Tommy Soderberg',style:'defensive'},Belgium:{rating:73,manager:'Robert Waseige',style:'defensive'},
    Norway:{rating:72,manager:'Egil Olsen',style:'defensive'},Slovenia:{rating:67,manager:'Srecko Katanec',style:'defensive'},
  },
  allFixtures:[
    {id:'e00_G1',home:'England',away:'Portugal',group:'A',stage:'group',date:'2000-06-12',neutral:true,historicResult:{home:2,away:3}},
    {id:'e00_G2',home:'Romania',away:'Germany',group:'A',stage:'group',date:'2000-06-11',neutral:true,historicResult:{home:1,away:1}},
    {id:'e00_G3',home:'England',away:'Germany',group:'A',stage:'group',date:'2000-06-17',neutral:true,historicResult:{home:1,away:0}},
    {id:'e00_G4',home:'Portugal',away:'Romania',group:'A',stage:'group',date:'2000-06-17',neutral:true,historicResult:{home:1,away:0}},
    {id:'e00_G5',home:'England',away:'Romania',group:'A',stage:'group',date:'2000-06-20',neutral:true,historicResult:{home:2,away:3}},
    {id:'e00_G6',home:'Portugal',away:'Germany',group:'A',stage:'group',date:'2000-06-20',neutral:true,historicResult:{home:3,away:0}},
    {id:'e00_QF1',home:'A_1',away:'B_2',stage:'qf',date:'2000-06-25',neutral:true},
    {id:'e00_SF1',home:'e00_QF1_W',away:'e00_QF2_W',stage:'sf',date:'2000-06-28',neutral:true},
    {id:'e00_F',home:'e00_SF1_W',away:'e00_SF2_W',stage:'final',date:'2000-07-02',neutral:true},
  ],
  knockoutStructure:{qf:[{fixtureId:'e00_QF1'}],sf:[{fixtureId:'e00_SF1'}],final:{fixtureId:'e00_F'}},
  squads:{
    England:['Alan Shearer','Michael Owen','Paul Scholes','Steven Gerrard','David Beckham','Nicky Butt','Tony Adams','Sol Campbell','Gareth Southgate','Rio Ferdinand','Gary Neville','Phil Neville','Ashley Cole','David James','Nigel Martyn','Robbie Fowler','Emile Heskey','Andy Cole','Kieron Dyer','Steve McManaman','Trevor Sinclair'],
    France:["Zinedine Zidane","Thierry Henry","Patrick Vieira","Laurent Blanc","Fabien Barthez"],
    Italy:["Francesco Totti","Alessandro Del Piero","Gianluca Zambrotta","Gianluigi Buffon"],
    Portugal:["Luis Figo","Rui Costa","Joao Pinto","Sergio Conceicao"],
  },
  commentary:{context:["Keegan's England. Shearer's last big tournament. Owen must deliver."],groupStage:["Portugal first — their Figo is world class.","Germany — a winnable game."],goodResult:["Owen is devastating on the counter."],badResult:["Keegan looks lost tactically."]},
  historicalNotes:{groupResult:'3rd in Group A — lost Portugal 2-3, beat Germany 1-0, lost Romania 2-3',knockoutRun:'Eliminated in group stage. Keegan resigned in the toilets at Wembley.',topScorer:'Alan Shearer 2 goals',keyMoment:"Ionel Ganea's last-minute winner for Romania. Phil Neville penalty foul. Keegan resigns."},
};