window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['euro2024']={
  key:'euro2024',name:'UEFA European Championship',fullName:'UEFA Euro 2024',
  year:2024,host:'Germany',startDate:'2024-06-14',endDate:'2024-07-14',
  tagline:"Southgate's last stand. Bellingham and Watkins heroes. Penalty final heartbreak.",
  qualifyingRequired:true,qualifierGroup:'ECQ_EURO2024_C',format:'euros_24',
  colours:{primary:'#000000',secondary:'#DD0000',accent:'#FFCC00',text:'#fff',bg:'#0A0000',bgCard:'#150000'},
  atmosphere:{context:"Southgate's final tournament. Germany hosts. Bellingham is the superstar. England grind through to the final and lose to Spain. Another penalty heartbreak.",pressureLevel:'extreme',mediaExpectation:'Win the tournament. No more excuses.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'Germany',flag:'🇩🇪',rating:84}, {name:'Scotland',flag:'🏴U000e0067U000e0062U000e0073U000e0063U000e0074U000e007f',rating:74}, {name:'Hungary',flag:'🇭🇺',rating:71}, {name:'Switzerland',flag:'🇨🇭',rating:79}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'Spain',flag:'🇪🇸',rating:90}, {name:'Croatia',flag:'🇭🇷',rating:78}, {name:'Italy',flag:'🇮🇹',rating:80}, {name:'Albania',flag:'🇦🇱',rating:68}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'England',flag:'🏴U000e0067U000e0062U000e0065U000e006eU000e0067U000e007f',rating:86}, {name:'Serbia',flag:'🇷🇸',rating:76}, {name:'Denmark',flag:'🇩🇰',rating:78}, {name:'Slovenia',flag:'🇸🇮',rating:70}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'France',flag:'🇫🇷',rating:88}, {name:'Austria',flag:'🇦🇹',rating:77}, {name:'Netherlands',flag:'🇳🇱',rating:83}, {name:'Poland',flag:'🇵🇱',rating:73}]},
  {id:'E',name:'Group E',qualified:2,teams:[{name:'Belgium',flag:'🇧🇪',rating:82}, {name:'Slovakia',flag:'🇸🇰',rating:72}, {name:'Romania',flag:'🇷🇴',rating:72}, {name:'Ukraine',flag:'🇺🇦',rating:74}]},
  {id:'F',name:'Group F',qualified:2,teams:[{name:'Turkey',flag:'🇹🇷',rating:78}, {name:'Georgia',flag:'🇬🇪',rating:70}, {name:'Portugal',flag:'🇵🇹',rating:85}, {name:'Czech Republic',flag:'🇨🇿',rating:73}]},
],
  teams:{
    England:{rating:86,manager:'Gareth Southgate',style:'balanced'},Spain:{rating:90,manager:'Luis de la Fuente',style:'attacking'},
    France:{rating:88,manager:'Didier Deschamps',style:'attacking'},Germany:{rating:84,manager:'Julian Nagelsmann',style:'attacking'},
    Portugal:{rating:85,manager:'Roberto Martinez',style:'attacking'},Netherlands:{rating:83,manager:'Ronald Koeman',style:'attacking'},
    Belgium:{rating:82,manager:'Domenico Tedesco',style:'attacking'},Switzerland:{rating:79,manager:'Murat Yakin',style:'balanced'},
    Turkey:{rating:78,manager:'Vincenzo Montella',style:'balanced'},Italy:{rating:80,manager:'Luciano Spalletti',style:'attacking'},
    Austria:{rating:77,manager:'Ralf Rangnick',style:'pressing'},Croatia:{rating:78,manager:'Zlatko Dalic',style:'balanced'},
    Denmark:{rating:78,manager:'Kasper Hjulmand',style:'balanced'},Ukraine:{rating:74,manager:'Serhiy Rebrov',style:'balanced'},
    Romania:{rating:72,manager:'Edward Iordanescu',style:'defensive'},Slovakia:{rating:72,manager:'Francesco Calzona',style:'defensive'},
    Slovenia:{rating:70,manager:'Matjaz Kek',style:'defensive'},Serbia:{rating:76,manager:'Dragan Stojkovic',style:'balanced'},
    Hungary:{rating:71,manager:'Marco Rossi',style:'defensive'},Poland:{rating:73,manager:'Michal Probierz',style:'balanced'},
    Georgia:{rating:70,manager:'Willy Sagnol',style:'defensive'},Albania:{rating:68,manager:'Sylvinho',style:'defensive'},
    Scotland:{rating:74,manager:'Steve Clarke',style:'defensive'},'Czech Republic':{rating:73,manager:'Ivan Hasek',style:'balanced'},
  },
  allFixtures:[
    {id:'e24_G1',home:'England',away:'Serbia',group:'C',stage:'group',date:'2024-06-16',neutral:true,historicResult:{home:1,away:0}},
    {id:'e24_G2',home:'Denmark',away:'Slovenia',group:'C',stage:'group',date:'2024-06-16',neutral:true,historicResult:{home:1,away:1}},
    {id:'e24_G3',home:'England',away:'Denmark',group:'C',stage:'group',date:'2024-06-20',neutral:true,historicResult:{home:1,away:1}},
    {id:'e24_G4',home:'Serbia',away:'Slovenia',group:'C',stage:'group',date:'2024-06-20',neutral:true,historicResult:{home:1,away:1}},
    {id:'e24_G5',home:'England',away:'Slovenia',group:'C',stage:'group',date:'2024-06-25',neutral:true,historicResult:{home:0,away:0}},
    {id:'e24_G6',home:'Serbia',away:'Denmark',group:'C',stage:'group',date:'2024-06-25',neutral:true,historicResult:{home:0,away:0}},
    {id:'e24_R1',home:'ENG_OF_C',away:'Slovakia',stage:'r16',date:'2024-06-30',neutral:true,historicResult:{home:2,away:1}},
    {id:'e24_QF1',home:'e24_R1_W',away:'e24_R4_W',stage:'qf',date:'2024-07-06',neutral:true},
    {id:'e24_SF1',home:'e24_QF1_W',away:'e24_QF2_W',stage:'sf',date:'2024-07-10',neutral:true},
    {id:'e24_F',home:'e24_SF1_W',away:'e24_SF2_W',stage:'final',date:'2024-07-14',neutral:true},
  ],
  knockoutStructure:{r16:[{fixtureId:'e24_R1'}],qf:[{fixtureId:'e24_QF1'}],sf:[{fixtureId:'e24_SF1'}],final:{fixtureId:'e24_F'}},
  squads:{
    England:['Harry Kane','Bukayo Saka','Jude Bellingham','Phil Foden','Raheem Sterling','Declan Rice','Kobbie Mainoo','Trent Alexander-Arnold','Kyle Walker','Kieran Trippier','Harry Maguire','John Stones','Marc Guehi','Jordan Pickford','Aaron Ramsdale','Marcus Rashford','Jack Grealish','Cole Palmer','Eberechi Eze','Ollie Watkins','Ivan Toney','Ezri Konsa','Luke Shaw','Ben Chilwell'],
    Spain:["Lamine Yamal","Nico Williams","Fabian Ruiz","Rodri","Dani Carvajal","Alvaro Morata"],
    France:["Kylian Mbappe","Antoine Griezmann","Aurelien Tchouameni","William Saliba"],
    Germany:["Florian Wirtz","Jamal Musiala","Kai Havertz","Manuel Neuer","Antonio Rudiger"],
  },
  commentary:{context:["Southgate's final tournament. Bellingham the superstar. Final awaits."],groupStage:["Serbia first — Bellingham's overhead kick.","Denmark: a draw feels like a step back."],goodResult:["Bellingham is world class."],badResult:["We need more from Foden and Saka."]},
  historicalNotes:{groupResult:'1st in Group C — beat Serbia 1-0, drew Denmark 1-1, drew Slovenia 0-0',knockoutRun:'Beat Slovakia (Bellingham 95th min), Switzerland, Netherlands, lost to Spain 1-2 in final',topScorer:'Harry Kane 3 goals',keyMoment:"Bellingham scissor kick vs Slovakia in 95th minute. Ollie Watkins vs Netherlands semi-final winner. Then Spain win the final."},
};