window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['russia18']={
  key:'russia18',name:'FIFA World Cup',fullName:'2018 FIFA World Cup',
  year:2018,host:'Russia',startDate:'2018-06-14',endDate:'2018-07-15',
  tagline:"Set-piece specialists. Kane's Golden Boot. Heartbreak vs Croatia.",
  qualifyingRequired:true,qualifierGroup:'WCQ_2018_F',format:'world_cup_32',
  colours:{primary:'#CC1122',secondary:'#D4AF37',accent:'#4488CC',text:'#fff',bg:'#0A0A0A',bgCard:'#1A0A0A'},
  atmosphere:{context:"Southgate's young England are set-piece specialists. Kane is the striker England have waited for. A genuine chance to go deep.",pressureLevel:'medium',mediaExpectation:'Quarter-finals. The nation dares to dream.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'Russia',flag:'🇷🇺',rating:76}, {name:'Saudi Arabia',flag:'🇸🇦',rating:68}, {name:'Egypt',flag:'🇪🇬',rating:72}, {name:'Uruguay',flag:'🇺🇾',rating:82}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'Portugal',flag:'🇵🇹',rating:82}, {name:'Spain',flag:'🇪🇸',rating:85}, {name:'Morocco',flag:'🇲🇦',rating:73}, {name:'Iran',flag:'🇮🇷',rating:70}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'France',flag:'🇫🇷',rating:88}, {name:'Australia',flag:'🇦🇺',rating:72}, {name:'Peru',flag:'🇵🇪',rating:74}, {name:'Denmark',flag:'🇩🇰',rating:75}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'Argentina',flag:'🇦🇷',rating:84}, {name:'Iceland',flag:'🇮🇸',rating:72}, {name:'Croatia',flag:'🇭🇷',rating:82}, {name:'Nigeria',flag:'🇳🇬',rating:74}]},
  {id:'E',name:'Group E',qualified:2,teams:[{name:'Brazil',flag:'🇧🇷',rating:86}, {name:'Switzerland',flag:'🇨🇭',rating:77}, {name:'Costa Rica',flag:'🇨🇷',rating:73}, {name:'Serbia',flag:'🇷🇸',rating:75}]},
  {id:'F',name:'Group F',qualified:2,teams:[{name:'Germany',flag:'🇩🇪',rating:85}, {name:'Mexico',flag:'🇲🇽',rating:78}, {name:'Sweden',flag:'🇸🇪',rating:76}, {name:'South Korea',flag:'🇰🇷',rating:72}]},
  {id:'G',name:'Group G',qualified:2,teams:[{name:'England',flag:'🏴U000e0067U000e0062U000e0065U000e006eU000e0067U000e007f',rating:83}, {name:'Belgium',flag:'🇧🇪',rating:84}, {name:'Tunisia',flag:'🇹🇳',rating:70}, {name:'Panama',flag:'🇵🇦',rating:67}]},
  {id:'H',name:'Group H',qualified:2,teams:[{name:'Poland',flag:'🇵🇱',rating:76}, {name:'Senegal',flag:'🇸🇳',rating:75}, {name:'Colombia',flag:'🇨🇴',rating:79}, {name:'Japan',flag:'🇯🇵',rating:74}]},
],
  teams:{
    England:{rating:83,manager:'Gareth Southgate',style:'defensive'},France:{rating:88,manager:'Didier Deschamps',style:'balanced'},
    Brazil:{rating:86,manager:'Tite',style:'attacking'},Germany:{rating:85,manager:'Joachim Low',style:'balanced'},
    Spain:{rating:85,manager:'Fernando Hierro',style:'attacking'},Belgium:{rating:84,manager:'Roberto Martinez',style:'attacking'},
    Argentina:{rating:84,manager:'Jorge Sampaoli',style:'attacking'},Croatia:{rating:82,manager:'Zlatko Dalic',style:'balanced'},
    Uruguay:{rating:82,manager:'Oscar Tabarez',style:'defensive'},Portugal:{rating:82,manager:'Fernando Santos',style:'balanced'},
    Colombia:{rating:79,manager:'Jose Pekerman',style:'balanced'},Mexico:{rating:78,manager:'Juan Carlos Osorio',style:'balanced'},
    Russia:{rating:76,manager:'Stanislav Cherchesov',style:'defensive'},Sweden:{rating:76,manager:'Janne Andersson',style:'defensive'},
    Denmark:{rating:75,manager:'Age Hareide',style:'defensive'},Switzerland:{rating:77,manager:'Vladimir Petkovic',style:'defensive'},
    Senegal:{rating:75,manager:'Aliou Cisse',style:'balanced'},Japan:{rating:74,manager:'Akira Nishino',style:'balanced'},
    Poland:{rating:76,manager:'Adam Nawalka',style:'balanced'},'South Korea':{rating:72,manager:'Shin Tae-yong',style:'balanced'},
    Australia:{rating:72,manager:'Bert van Marwijk',style:'defensive'},Nigeria:{rating:74,manager:'Gernot Rohr',style:'balanced'},
    Morocco:{rating:73,manager:'Herve Renard',style:'defensive'},Peru:{rating:74,manager:'Ricardo Gareca',style:'balanced'},
    Serbia:{rating:75,manager:'Mladen Krstajic',style:'balanced'},Iceland:{rating:72,manager:'Heimir Hallgrimsson',style:'defensive'},
    Iran:{rating:70,manager:'Carlos Queiroz',style:'defensive'},Tunisia:{rating:70,manager:'Nabil Maaloul',style:'defensive'},
    Panama:{rating:67,manager:'Hernan Dario Gomez',style:'defensive'},'Costa Rica':{rating:73,manager:'Oscar Ramirez',style:'defensive'},
    Egypt:{rating:72,manager:'Hector Cuper',style:'defensive'},'Saudi Arabia':{rating:68,manager:'Juan Antonio Pizzi',style:'balanced'},
  },
  allFixtures:[
    {id:'r18_G1',home:'England',away:'Tunisia',group:'G',stage:'group',date:'2018-06-18',neutral:true,historicResult:{home:2,away:1}},
    {id:'r18_G2',home:'Belgium',away:'Panama',group:'G',stage:'group',date:'2018-06-18',neutral:true,historicResult:{home:3,away:0}},
    {id:'r18_G3',home:'England',away:'Panama',group:'G',stage:'group',date:'2018-06-24',neutral:true,historicResult:{home:6,away:1}},
    {id:'r18_G4',home:'Tunisia',away:'Belgium',group:'G',stage:'group',date:'2018-06-23',neutral:true,historicResult:{home:2,away:5}},
    {id:'r18_G5',home:'England',away:'Belgium',group:'G',stage:'group',date:'2018-06-28',neutral:true,historicResult:{home:0,away:1}},
    {id:'r18_G6',home:'Panama',away:'Tunisia',group:'G',stage:'group',date:'2018-06-28',neutral:true,historicResult:{home:1,away:2}},
    {id:'r18_R1',home:'G_1',away:'H_2',stage:'r16',date:'2018-07-03',neutral:true},
    {id:'r18_R2',home:'H_1',away:'G_2',stage:'r16',date:'2018-07-04',neutral:true},
    {id:'r18_QF1',home:'r18_R1_W',away:'r18_R2_W',stage:'qf',date:'2018-07-07',neutral:true},
    {id:'r18_SF1',home:'r18_QF1_W',away:'r18_QF2_W',stage:'sf',date:'2018-07-11',neutral:true},
    {id:'r18_3P',home:'r18_SF1_L',away:'r18_SF2_L',stage:'3rd',date:'2018-07-14',neutral:true},
    {id:'r18_F',home:'r18_SF1_W',away:'r18_SF2_W',stage:'final',date:'2018-07-15',neutral:true},
  ],
  knockoutStructure:{r16:[{fixtureId:'r18_R1'},{fixtureId:'r18_R2'}],qf:[{fixtureId:'r18_QF1'}],sf:[{fixtureId:'r18_SF1'}],final:{fixtureId:'r18_F'}},
  squads:{
    England:['Harry Kane','Raheem Sterling','Jesse Lingard','Jordan Henderson','Dele Alli','Fabian Delph','Eric Dier','Kyle Walker','Kieran Trippier','Harry Maguire','John Stones','Jordan Pickford','Marcus Rashford','Danny Welbeck','Gary Cahill','Phil Jones','Nick Pope','Jack Butland','Ashley Young','Danny Rose','Ruben Loftus-Cheek'],
    France:["Antoine Griezmann","Kylian Mbappe","Paul Pogba","N'Golo Kante","Hugo Lloris","Raphael Varane","Lucas Hernandez"],
    Croatia:['Luka Modric','Ivan Rakitic','Mario Mandzukic','Ivan Perisic','Dejan Lovren'],
    Belgium:['Eden Hazard','Romelu Lukaku','Kevin De Bruyne','Thibaut Courtois'],
  },
  commentary:{context:["Russia hosts. Set-piece specialists. Kane the Golden Boot favourite."],groupStage:["Tunisia first — must win.","Panama: a chance to score big."],goodResult:["Set pieces working perfectly."],badResult:["Southgate needs to be braver."]},
  historicalNotes:{groupResult:'Won Group G (beat Tunisia 2-1, Panama 6-1, lost to Belgium 0-1)',knockoutRun:'Beat Colombia (pens), Sweden 2-0, lost to Croatia 1-2 AET',topScorer:'Harry Kane — Golden Boot 6 goals',keyMoment:'Trippier free kick. Then Mandzukic heartbreak in extra time.'},
};