window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['euro2016']={
  key:'euro2016',name:'UEFA European Championship',fullName:'UEFA Euro 2016',
  year:2016,host:'France',startDate:'2016-06-10',endDate:'2016-07-10',
  tagline:"Iceland. Roy Hodgson resigns. A humiliation that changed English football.",
  qualifyingRequired:true,qualifierGroup:'ECQ_EURO2016_E',format:'euros_24',
  colours:{primary:'#002395',secondary:'#ED2939',accent:'#FFFFFF',text:'#fff',bg:'#00001A',bgCard:'#00000A'},
  atmosphere:{context:"Roy Hodgson's England limp through a group of three mediocre sides. Then Iceland. The nadir of English football.",pressureLevel:'high',mediaExpectation:'Minimum quarters. Expected semis.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'France',flag:'🇫🇷',rating:87}, {name:'Romania',flag:'🇷🇴',rating:69}, {name:'Albania',flag:'🇦🇱',rating:67}, {name:'Switzerland',flag:'🇨🇭',rating:77}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'England',flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿',rating:80}, {name:'Russia',flag:'🇷🇺',rating:72}, {name:'Wales',flag:'🏴󠁧󠁢󠁷󠁬󠁳󠁿',rating:76}, {name:'Slovakia',flag:'🇸🇰',rating:72}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'Germany',flag:'🇩🇪',rating:88}, {name:'Ukraine',flag:'🇺🇦',rating:71}, {name:'Poland',flag:'🇵🇱',rating:76}, {name:'Northern Ireland',flag:'🇮🇪',rating:68}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'Spain',flag:'🇪🇸',rating:86}, {name:'Czech Republic',flag:'🇨🇿',rating:73}, {name:'Turkey',flag:'🇹🇷',rating:73}, {name:'Croatia',flag:'🇭🇷',rating:79}]},
  {id:'E',name:'Group E',qualified:2,teams:[{name:'Belgium',flag:'🇧🇪',rating:84}, {name:'Italy',flag:'🇮🇹',rating:81}, {name:'Ireland',flag:'🇮🇪',rating:70}, {name:'Sweden',flag:'🇸🇪',rating:73}]},
  {id:'F',name:'Group F',qualified:2,teams:[{name:'Portugal',flag:'🇵🇹',rating:82}, {name:'Iceland',flag:'🇮🇸',rating:72}, {name:'Austria',flag:'🇦🇹',rating:74}, {name:'Hungary',flag:'🇭🇺',rating:71}]}
],
  teams:{
    England:{rating:80,manager:'Roy Hodgson',style:'defensive'},France:{rating:87,manager:'Didier Deschamps',style:'attacking'},
    Germany:{rating:88,manager:'Joachim Low',style:'balanced'},Spain:{rating:86,manager:'Vicente del Bosque',style:'attacking'},
    Belgium:{rating:84,manager:'Marc Wilmots',style:'attacking'},Portugal:{rating:82,manager:'Fernando Santos',style:'defensive'},
    Italy:{rating:81,manager:'Antonio Conte',style:'defensive'},Wales:{rating:76,manager:'Chris Coleman',style:'defensive'},
    Croatia:{rating:79,manager:'Ante Cacic',style:'balanced'},Iceland:{rating:72,manager:'Lars Lagerback',style:'defensive'},
    Switzerland:{rating:77,manager:'Vladimir Petkovic',style:'defensive'},Poland:{rating:76,manager:'Adam Nawalka',style:'balanced'},
    Russia:{rating:72,manager:'Leonid Slutsky',style:'defensive'},Slovakia:{rating:72,manager:'Jan Kozak',style:'defensive'},
    Hungary:{rating:71,manager:'Bernd Storck',style:'defensive'},Austria:{rating:74,manager:'Marcel Koller',style:'balanced'},
    Sweden:{rating:73,manager:'Erik Hamren',style:'defensive'},Ukraine:{rating:71,manager:'Mykhailo Fomenko',style:'balanced'},
    Turkey:{rating:73,manager:'Fatih Terim',style:'balanced'},'Czech Republic':{rating:73,manager:'Pavel Vrba',style:'balanced'},
    Romania:{rating:69,manager:'Anghel Iordanescu',style:'defensive'},Albania:{rating:67,manager:'Gianni De Biasi',style:'defensive'},
    Ireland:{rating:70,manager:'Martin O\'Neill',style:'defensive'},'Northern Ireland':{rating:68,manager:'Michael O\'Neill',style:'defensive'},
  },
  allFixtures:[
    {id:'e16_G1',home:'England',away:'Russia',group:'B',stage:'group',date:'2016-06-11',neutral:true,historicResult:{home:1,away:1}},
    {id:'e16_G2',home:'Wales',away:'Slovakia',group:'B',stage:'group',date:'2016-06-11',neutral:true,historicResult:{home:2,away:1}},
    {id:'e16_G3',home:'England',away:'Wales',group:'B',stage:'group',date:'2016-06-16',neutral:true,historicResult:{home:2,away:1}},
    {id:'e16_G4',home:'Russia',away:'Slovakia',group:'B',stage:'group',date:'2016-06-15',neutral:true,historicResult:{home:1,away:2}},
    {id:'e16_G5',home:'England',away:'Slovakia',group:'B',stage:'group',date:'2016-06-20',neutral:true,historicResult:{home:0,away:0}},
    {id:'e16_G6',home:'Russia',away:'Wales',group:'B',stage:'group',date:'2016-06-20',neutral:true,historicResult:{home:0,away:3}},
    {id:'e16_R1',home:'B_1',away:'A_3_or_C_3',stage:'r16',date:'2016-06-27',neutral:true},
    {id:'e16_QF1',home:'e16_R1_W',away:'e16_R5_W',stage:'qf',date:'2016-07-02',neutral:true},
    {id:'e16_SF1',home:'e16_QF1_W',away:'e16_QF2_W',stage:'sf',date:'2016-07-06',neutral:true},
    {id:'e16_F',home:'e16_SF1_W',away:'e16_SF2_W',stage:'final',date:'2016-07-10',neutral:true},
  ],
  knockoutStructure:{r16:[{fixtureId:'e16_R1'}],qf:[{fixtureId:'e16_QF1'}],sf:[{fixtureId:'e16_SF1'}],final:{fixtureId:'e16_F'}},
  squads:{
    England:['Harry Kane','Wayne Rooney','Raheem Sterling','Joe Hart','Gary Cahill','Chris Smalling','Kyle Walker','Danny Rose','Jordan Henderson','Eric Dier','Dele Alli','Adam Lallana','Andros Townsend','Jamie Vardy','Daniel Sturridge','Jack Wilshere','Kieran Gibbs','Phil Jagielka','John Stones','James Milner','Fraser Forster','Tom Heaton'],
    France:["Antoine Griezmann","Dimitri Payet","Paul Pogba","Raphael Varane","Hugo Lloris"],
    Germany:["Thomas Muller","Mesut Ozil","Toni Kroos","Manuel Neuer","Jerome Boateng"],
    Iceland:["Gylfi Sigurdsson","Aron Gunnarsson","Jon Dadi Bodvarsson"],
  },
  commentary:{context:["Roy Hodgson's England. Rooney waning. No clear system. Iceland lurk."],groupStage:["Must beat Russia — draw would be a disaster.","Wales derby — historic."],goodResult:["England looking more organised."],badResult:["Hodgson's 4-5-1 is strangling us."]},
  historicalNotes:{groupResult:'Finished 2nd in Group B — drew Russia 1-1, beat Wales 2-1, drew Slovakia 0-0',knockoutRun:'Lost to Iceland 1-2 in Round of 16. Hodgson resigned immediately.',topScorer:'Rooney, Sturridge, Vardy 1 goal each',keyMoment:"Ragnar Sigurdsson equaliser. Kolbeinn Sigthorsson winner. National humiliation."},
};