window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['euro2008']={
  key:'euro2008',name:'UEFA European Championship',fullName:'UEFA Euro 2008',
  year:2008,host:'Austria & Switzerland',startDate:'2008-06-07',endDate:'2008-06-29',
  tagline:"England didn't qualify. Steve McClaren's umbrella. A dark day.",
  qualifyingRequired:true,qualifierGroup:'ECQ_EURO2008_3',format:'euros_16',
  colours:{primary:'#C8102E',secondary:'#FFFFFF',accent:'#EF3340',text:'#fff',bg:'#0A0000',bgCard:'#150000'},
  atmosphere:{context:"England FAILED TO QUALIFY. McClaren stood under his umbrella as Croatia beat England. If you're here, you changed history.",pressureLevel:'extreme',mediaExpectation:'At least qualify, for goodness sake.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'England',flag:'🏴U000e0067U000e0062U000e0065U000e006eU000e0067U000e007f',rating:81}, {name:'Austria',flag:'🇦🇹',rating:69}, {name:'Poland',flag:'🇵🇱',rating:73}, {name:'Croatia',flag:'🇭🇷',rating:80}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'Germany',flag:'🇩🇪',rating:85}, {name:'Czech Republic',flag:'🇨🇿',rating:78}, {name:'Turkey',flag:'🇹🇷',rating:78}, {name:'Switzerland',flag:'🇨🇭',rating:74}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'Netherlands',flag:'🇳🇱',rating:88}, {name:'Italy',flag:'🇮🇹',rating:84}, {name:'Romania',flag:'🇷🇴',rating:72}, {name:'France',flag:'🇫🇷',rating:81}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'Spain',flag:'🇪🇸',rating:90}, {name:'Russia',flag:'🇷🇺',rating:78}, {name:'Sweden',flag:'🇸🇪',rating:76}, {name:'Greece',flag:'🇬🇷',rating:72}]},
],
  teams:{
    England:{rating:81,manager:'Steve McClaren',style:'balanced'},Spain:{rating:90,manager:'Luis Aragones',style:'attacking'},
    Germany:{rating:85,manager:'Joachim Low',style:'balanced'},Russia:{rating:78,manager:'Guus Hiddink',style:'balanced'},
    Netherlands:{rating:88,manager:'Marco van Basten',style:'attacking'},Turkey:{rating:78,manager:'Fatih Terim',style:'balanced'},
    Italy:{rating:84,manager:'Roberto Donadoni',style:'defensive'},Croatia:{rating:80,manager:'Slaven Bilic',style:'balanced'},
    'Czech Republic':{rating:78,manager:'Karel Bruckner',style:'balanced'},France:{rating:81,manager:'Raymond Domenech',style:'balanced'},
    Portugal:{rating:82,manager:'Luiz Felipe Scolari',style:'attacking'},Sweden:{rating:76,manager:'Lars Lagerback',style:'defensive'},
    Poland:{rating:73,manager:'Leo Beenhakker',style:'balanced'},Switzerland:{rating:74,manager:'Jakob Kuhn',style:'defensive'},
    Austria:{rating:69,manager:'Josef Hickersberger',style:'defensive'},Greece:{rating:72,manager:'Otto Rehhagel',style:'defensive'},
  },
  allFixtures:[
    {id:'e08_G1',home:'England',away:'Poland',group:'A',stage:'group',date:'2008-06-08',neutral:true},
    {id:'e08_G2',home:'Austria',away:'Croatia',group:'A',stage:'group',date:'2008-06-08',neutral:true,historicResult:{home:0,away:1}},
    {id:'e08_G3',home:'England',away:'Austria',group:'A',stage:'group',date:'2008-06-12',neutral:true},
    {id:'e08_G4',home:'Croatia',away:'Poland',group:'A',stage:'group',date:'2008-06-12',neutral:true,historicResult:{home:1,away:0}},
    {id:'e08_G5',home:'England',away:'Croatia',group:'A',stage:'group',date:'2008-06-16',neutral:true},
    {id:'e08_G6',home:'Poland',away:'Austria',group:'A',stage:'group',date:'2008-06-16',neutral:true,historicResult:{home:1,away:1}},
    {id:'e08_QF1',home:'A_1',away:'B_2',stage:'qf',date:'2008-06-20',neutral:true},
    {id:'e08_SF1',home:'e08_QF1_W',away:'e08_QF2_W',stage:'sf',date:'2008-06-25',neutral:true},
    {id:'e08_F',home:'e08_SF1_W',away:'e08_SF2_W',stage:'final',date:'2008-06-29',neutral:true},
  ],
  knockoutStructure:{qf:[{fixtureId:'e08_QF1'}],sf:[{fixtureId:'e08_SF1'}],final:{fixtureId:'e08_F'}},
  squads:{
    England:['Wayne Rooney','Michael Owen','Frank Lampard','Steven Gerrard','Joe Cole','Owen Hargreaves','Gareth Barry','Rio Ferdinand','John Terry','Ashley Cole','Gary Neville','Paul Robinson','Scott Carson','Wes Brown','Ledley King','Joleon Lescott','Shaun Wright-Phillips','Aaron Lennon','Stewart Downing','Peter Crouch','Jermain Defoe','Darren Bent'],
    Spain:["Fernando Torres","David Villa","Andres Iniesta","Xavi","Iker Casillas","Carles Puyol"],
    Germany:["Michael Ballack","Miroslav Klose","Bastian Schweinsteiger","Jens Lehmann"],
    Netherlands:["Robin van Persie","Arjen Robben","Ruud van Nistelrooy","Edwin van der Sar"],
  },
  commentary:{context:["England DIDN'T qualify historically — McClaren's umbrella. If you're here, you changed it."],groupStage:["Poland first — should win.","Croatia — payback for qualifying."],goodResult:["England looking organised."],badResult:["Same old problems. No creativity."]},
  historicalNotes:{groupResult:'England failed to qualify historically — Croatia 3-2 in qualifying',knockoutRun:'Alternate history only',topScorer:'Fernando Torres won Golden Boot',keyMoment:"Scott Carson drops an absolute sitter in qualifying. McClaren stands under his umbrella."},
};