window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['euro2004']={
  key:'euro2004',name:'UEFA European Championship',fullName:'UEFA Euro 2004',
  year:2004,host:'Portugal',startDate:'2004-06-12',endDate:'2004-07-04',
  tagline:"Sven's England, Rooney's debut, Gerrard, Lampard — and Darius Vassell loses the penalty.",
  qualifyingRequired:true,qualifierGroup:'ECQ_EURO2004_7',format:'euros_16',
  colours:{primary:'#006600',secondary:'#FF0000',accent:'#FFFFFF',text:'#fff',bg:'#000A00',bgCard:'#001A00'},
  atmosphere:{context:"Sven's best England squad. Rooney is 18 and unstoppable. Beckham is captain. This could finally be the time. Lampard scoring, Gerrard scoring — then Portugal penalties.",pressureLevel:'high',mediaExpectation:'Semi-finals. Possibly more.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'Portugal',flag:'🇵🇹',rating:85}, {name:'Greece',flag:'🇬🇷',rating:76}, {name:'Spain',flag:'🇪🇸',rating:83}, {name:'Russia',flag:'🇷🇺',rating:72}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'England',flag:'🏴U000e0067U000e0062U000e0065U000e006eU000e0067U000e007f',rating:83}, {name:'France',flag:'🇫🇷',rating:88}, {name:'Switzerland',flag:'🇨🇭',rating:74}, {name:'Croatia',flag:'🇭🇷',rating:79}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'Denmark',flag:'🇩🇰',rating:77}, {name:'Italy',flag:'🇮🇹',rating:84}, {name:'Sweden',flag:'🇸🇪',rating:79}, {name:'Bulgaria',flag:'🇧🇬',rating:70}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'Czech Republic',flag:'🇨🇿',rating:82}, {name:'Germany',flag:'🇩🇪',rating:78}, {name:'Latvia',flag:'🇱🇻',rating:65}, {name:'Netherlands',flag:'🇳🇱',rating:84}]},
],
  teams:{
    England:{rating:83,manager:'Sven-Goran Eriksson',style:'attacking'},France:{rating:88,manager:'Jacques Santini',style:'attacking'},
    Portugal:{rating:85,manager:'Luiz Felipe Scolari',style:'attacking'},Netherlands:{rating:84,manager:'Dick Advocaat',style:'attacking'},
    'Czech Republic':{rating:82,manager:'Karel Bruckner',style:'attacking'},Sweden:{rating:79,manager:'Lars Lagerback',style:'defensive'},
    Greece:{rating:76,manager:'Otto Rehhagel',style:'defensive'},Germany:{rating:78,manager:'Rudi Voller',style:'balanced'},
    Italy:{rating:84,manager:'Giovanni Trapattoni',style:'defensive'},Spain:{rating:83,manager:'Inaki Saez',style:'attacking'},
    Denmark:{rating:77,manager:'Morten Olsen',style:'balanced'},Croatia:{rating:79,manager:'Otto Baric',style:'balanced'},
    Switzerland:{rating:74,manager:'Jakob Kuhn',style:'defensive'},Russia:{rating:72,manager:'Georgi Yartsev',style:'balanced'},
    Bulgaria:{rating:70,manager:'Plamen Markov',style:'defensive'},Latvia:{rating:65,manager:'Aleksandrs Starkovs',style:'defensive'},
  },
  allFixtures:[
    {id:'e04_G1',home:'England',away:'France',group:'B',stage:'group',date:'2004-06-13',neutral:true,historicResult:{home:1,away:2}},
    {id:'e04_G2',home:'Croatia',away:'Switzerland',group:'B',stage:'group',date:'2004-06-13',neutral:true,historicResult:{home:2,away:0}},
    {id:'e04_G3',home:'England',away:'Switzerland',group:'B',stage:'group',date:'2004-06-17',neutral:true,historicResult:{home:3,away:0}},
    {id:'e04_G4',home:'France',away:'Croatia',group:'B',stage:'group',date:'2004-06-17',neutral:true,historicResult:{home:2,away:2}},
    {id:'e04_G5',home:'England',away:'Croatia',group:'B',stage:'group',date:'2004-06-21',neutral:true,historicResult:{home:4,away:2}},
    {id:'e04_G6',home:'France',away:'Switzerland',group:'B',stage:'group',date:'2004-06-21',neutral:true,historicResult:{home:3,away:1}},
    {id:'e04_QF1',home:'ENG_OF_B',away:'Portugal',stage:'qf',date:'2004-06-24',neutral:true,historicResult:{home:2,away:2}},
    {id:'e04_SF1',home:'e04_QF1_W',away:'e04_QF2_W',stage:'sf',date:'2004-06-30',neutral:true},
    {id:'e04_F',home:'e04_SF1_W',away:'e04_SF2_W',stage:'final',date:'2004-07-04',neutral:true},
  ],
  knockoutStructure:{qf:[{fixtureId:'e04_QF1'}],sf:[{fixtureId:'e04_SF1'}],final:{fixtureId:'e04_F'}},
  squads:{
    England:['Wayne Rooney','Michael Owen','David Beckham','Frank Lampard','Steven Gerrard','Nicky Butt','Paul Scholes','Sol Campbell','Rio Ferdinand','Ashley Cole','Gary Neville','David James','Ian Walker','Paul Robinson','John Terry','Phil Neville','Wayne Bridge','Ledley King','Emile Heskey','Darius Vassell','Kieron Dyer','Joe Cole'],
    France:["Zinedine Zidane","Thierry Henry","Patrick Vieira","Claude Makelele","Fabien Barthez"],
    Portugal:["Luis Figo","Cristiano Ronaldo","Rui Costa","Deco","Ricardo"],
    'Czech Republic':["Pavel Nedved","Jan Koller","Petr Cech","Tomas Rosicky"],
  },
  commentary:{context:["Sven's best squad. Rooney is 18 and unstoppable. Beckham captain."],groupStage:["France first — lose to them was history.","Switzerland — big win please."],goodResult:["Rooney is extraordinary."],badResult:["Beckham keeps missing penalties."]},
  historicalNotes:{groupResult:'2nd in Group B — lost France 1-2, beat Switzerland 3-0, beat Croatia 4-2',knockoutRun:'Beat Switzerland, lost to Portugal on penalties in QF',topScorer:'Wayne Rooney 4 goals',keyMoment:"Rooney's broken metatarsal. Beckham misses penalty vs Portugal. Vassell's penalty saved."},
};