window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['southafrica10']={
  key:'southafrica10',name:'FIFA World Cup',fullName:'2010 FIFA World Cup',
  year:2010,host:'South Africa',startDate:'2010-06-11',endDate:'2010-07-11',
  tagline:"The vuvuzela World Cup. Green's howler. 4-1 humiliation by Germany.",
  qualifyingRequired:true,qualifierGroup:'WCQ_2010_6',format:'world_cup_32',
  colours:{primary:'#007A4D',secondary:'#FFB81C',accent:'#FFFFFF',text:'#fff',bg:'#00100A',bgCard:'#001A0A'},
  atmosphere:{context:"Capello's England are the Golden Generation's last stand. Rooney, Gerrard, Lampard, Terry, Ferdinand. They should do it. Green drops a sitter. Germany hammer them.",pressureLevel:'very_high',mediaExpectation:'Semi-finals minimum. Golden Generation must deliver NOW.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'South Africa',flag:'🇿🇦',rating:70}, {name:'Mexico',flag:'🇲🇽',rating:77}, {name:'Uruguay',flag:'🇺🇾',rating:80}, {name:'France',flag:'🇫🇷',rating:80}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'Argentina',flag:'🇦🇷',rating:87}, {name:'Nigeria',flag:'🇳🇬',rating:72}, {name:'South Korea',flag:'🇰🇷',rating:75}, {name:'Greece',flag:'🇬🇷',rating:71}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'England',flag:'🏴U000e0067U000e0062U000e0065U000e006eU000e0067U000e007f',rating:83}, {name:'USA',flag:'🇺🇸',rating:75}, {name:'Algeria',flag:'🇩🇿',rating:69}, {name:'Slovenia',flag:'🇸🇮',rating:71}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'Germany',flag:'🇩🇪',rating:87}, {name:'Australia',flag:'🇦🇺',rating:71}, {name:'Serbia',flag:'🇷🇸',rating:74}, {name:'Ghana',flag:'🇬🇭',rating:76}]},
  {id:'E',name:'Group E',qualified:2,teams:[{name:'Netherlands',flag:'🇳🇱',rating:85}, {name:'Denmark',flag:'🇩🇰',rating:73}, {name:'Japan',flag:'🇯🇵',rating:72}, {name:'Cameroon',flag:'🇨🇲',rating:72}]},
  {id:'F',name:'Group F',qualified:2,teams:[{name:'Italy',flag:'🇮🇹',rating:83}, {name:'Paraguay',flag:'🇵🇾',rating:74}, {name:'New Zealand',flag:'🇳🇿',rating:64}, {name:'Slovakia',flag:'🇸🇰',rating:72}]},
  {id:'G',name:'Group G',qualified:2,teams:[{name:'Brazil',flag:'🇧🇷',rating:88}, {name:'North Korea',flag:'🇰🇵',rating:62}, {name:'Ivory Coast',flag:'🇨🇮',rating:78}, {name:'Portugal',flag:'🇵🇹',rating:82}]},
  {id:'H',name:'Group H',qualified:2,teams:[{name:'Spain',flag:'🇪🇸',rating:90}, {name:'Switzerland',flag:'🇨🇭',rating:76}, {name:'Honduras',flag:'🇭🇳',rating:65}, {name:'Chile',flag:'🇨🇱',rating:78}]},
],
  teams:{
    England:{rating:83,manager:'Fabio Capello',style:'defensive'},Brazil:{rating:88,manager:'Dunga',style:'attacking'},
    Argentina:{rating:87,manager:'Diego Maradona',style:'attacking'},Spain:{rating:90,manager:'Vicente del Bosque',style:'attacking'},
    Germany:{rating:87,manager:'Joachim Low',style:'balanced'},Netherlands:{rating:85,manager:'Bert van Marwijk',style:'balanced'},
    Uruguay:{rating:80,manager:'Oscar Tabarez',style:'defensive'},Ghana:{rating:76,manager:'Milovan Rajevac',style:'balanced'},
    USA:{rating:75,manager:'Bob Bradley',style:'defensive'},Mexico:{rating:77,manager:'Javier Aguirre',style:'balanced'},
    'South Korea':{rating:75,manager:'Huh Jung-moo',style:'balanced'},Portugal:{rating:82,manager:'Carlos Queiroz',style:'balanced'},
    Italy:{rating:83,manager:'Marcello Lippi',style:'defensive'},Paraguay:{rating:74,manager:'Gerardo Martino',style:'defensive'},
    Chile:{rating:78,manager:'Marcelo Bielsa',style:'attacking'},'South Africa':{rating:70,manager:'Carlos Alberto Parreira',style:'balanced'},
    'Ivory Coast':{rating:78,manager:'Sven-Goran Eriksson',style:'balanced'},Algeria:{rating:69,manager:'Rabah Saadane',style:'defensive'},
    Slovenia:{rating:71,manager:'Matjaz Kek',style:'defensive'},Greece:{rating:71,manager:'Otto Rehhagel',style:'defensive'},
    Serbia:{rating:74,manager:'Radomir Antic',style:'balanced'},Nigeria:{rating:72,manager:'Lars Lagerback',style:'balanced'},
    Japan:{rating:72,manager:'Takeshi Okada',style:'balanced'},Denmark:{rating:73,manager:'Morten Olsen',style:'balanced'},
    Australia:{rating:71,manager:'Pim Verbeek',style:'defensive'},Slovakia:{rating:72,manager:'Vladimir Weiss',style:'balanced'},
    'North Korea':{rating:62,manager:'Kim Jong-hun',style:'defensive'},Honduras:{rating:65,manager:'Reinaldo Rueda',style:'defensive'},
    Cameroon:{rating:72,manager:'Paul Le Guen',style:'balanced'},'New Zealand':{rating:64,manager:'Ricki Herbert',style:'defensive'},
    Switzerland:{rating:76,manager:'Ottmar Hitzfeld',style:'defensive'},France:{rating:80,manager:'Raymond Domenech',style:'balanced'},
  },
  allFixtures:[
    {id:'sa10_G1',home:'England',away:'USA',group:'C',stage:'group',date:'2010-06-12',neutral:true,historicResult:{home:1,away:1}},
    {id:'sa10_G2',home:'Algeria',away:'Slovenia',group:'C',stage:'group',date:'2010-06-13',neutral:true,historicResult:{home:0,away:1}},
    {id:'sa10_G3',home:'England',away:'Algeria',group:'C',stage:'group',date:'2010-06-18',neutral:true,historicResult:{home:0,away:0}},
    {id:'sa10_G4',home:'USA',away:'Slovenia',group:'C',stage:'group',date:'2010-06-18',neutral:true,historicResult:{home:2,away:2}},
    {id:'sa10_G5',home:'England',away:'Slovenia',group:'C',stage:'group',date:'2010-06-23',neutral:true,historicResult:{home:1,away:0}},
    {id:'sa10_G6',home:'USA',away:'Algeria',group:'C',stage:'group',date:'2010-06-23',neutral:true,historicResult:{home:1,away:0}},
    {id:'sa10_R1',home:'ENG_OF_C',away:'Germany',stage:'r16',date:'2010-06-27',venue:'Free State Stadium',neutral:true,historicResult:{home:1,away:4}},
    {id:'sa10_QF1',home:'sa10_R1_W',away:'sa10_R2_W',stage:'qf',date:'2010-07-03',neutral:true},
    {id:'sa10_SF1',home:'sa10_QF1_W',away:'sa10_QF2_W',stage:'sf',date:'2010-07-07',neutral:true},
    {id:'sa10_3P',home:'sa10_SF1_L',away:'sa10_SF2_L',stage:'3rd',date:'2010-07-10',neutral:true},
    {id:'sa10_F',home:'sa10_SF1_W',away:'sa10_SF2_W',stage:'final',date:'2010-07-11',neutral:true},
  ],
  knockoutStructure:{r16:[{fixtureId:'sa10_R1'}],qf:[{fixtureId:'sa10_QF1'}],sf:[{fixtureId:'sa10_SF1'}],final:{fixtureId:'sa10_F'}},
  squads:{
    England:['Wayne Rooney','Steven Gerrard','Frank Lampard','Joe Hart','Robert Green','John Terry','Rio Ferdinand','Glen Johnson','Ashley Cole','Gareth Barry','Michael Carrick','James Milner','Shaun Wright-Phillips','Aaron Lennon','Emile Heskey','Peter Crouch','Jermain Defoe','Matthew Upson','Jamie Carragher','Ledley King','Michael Dawson'],
    Spain:["David Villa","Andres Iniesta","Xavi","Iker Casillas","Carles Puyol","Gerard Pique"],
    Germany:["Thomas Muller","Miroslav Klose","Mesut Ozil","Manuel Neuer","Philipp Lahm"],
    Argentina:["Lionel Messi","Carlos Tevez","Gonzalo Higuain","Javier Mascherano"],
  },
  commentary:{context:["Capello's Golden Generation. Vuvuzelas. Must deliver."],groupStage:["USA first — don't drop it like Green.","Algeria — must not be as bad as it was."],goodResult:["Gerrard is leading us."],badResult:["Rooney looks off-colour. Capello is too cautious."]},
  historicalNotes:{groupResult:'2nd in Group C — drew USA 1-1, drew Algeria 0-0, beat Slovenia 1-0',knockoutRun:'Beat Germany? Or historically lost 4-1. Lampard goal disallowed.',topScorer:'Jermain Defoe 1 goal',keyMoment:"Robert Green drops Dempsey's tame shot. Lampard goal not given. 4-1 to Germany."},
};