window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['euro2020']={
  key:'euro2020',name:'UEFA European Championship',fullName:'UEFA Euro 2020',
  year:2021,host:'Various (pan-European)',startDate:'2021-06-11',endDate:'2021-07-11',
  tagline:"It was coming home. Then Saka stepped up. Penalty heartbreak at Wembley.",
  qualifyingRequired:true,qualifierGroup:'ECQ_EURO2020_A',format:'euros_24',
  colours:{primary:'#003DA5',secondary:'#E8E8E8',accent:'#00A0E9',text:'#fff',bg:'#000A1A',bgCard:'#001020'},
  atmosphere:{context:"Delayed by COVID, played in 2021. England reach the final at Wembley. The nation is swept up in it. Then it all goes wrong on penalties.",pressureLevel:'extreme',mediaExpectation:'It is LITERALLY coming home.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'Turkey',flag:'🇹🇷',rating:73}, {name:'Italy',flag:'🇮🇹',rating:87}, {name:'Wales',flag:'🏴U000e0067U000e0062U000e0077U000e006cU000e0073U000e007f',rating:74}, {name:'Switzerland',flag:'🇨🇭',rating:78}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'Denmark',flag:'🇩🇰',rating:80}, {name:'Finland',flag:'🇫🇮',rating:69}, {name:'Belgium',flag:'🇧🇪',rating:85}, {name:'Russia',flag:'🇷🇺',rating:71}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'Netherlands',flag:'🇳🇱',rating:82}, {name:'Ukraine',flag:'🇺🇦',rating:76}, {name:'Austria',flag:'🇦🇹',rating:75}, {name:'North Macedonia',flag:'🇲🇰',rating:67}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'England',flag:'🏴U000e0067U000e0062U000e0065U000e006eU000e0067U000e007f',rating:85}, {name:'Croatia',flag:'🇭🇷',rating:80}, {name:'Scotland',flag:'🏴U000e0067U000e0062U000e0073U000e0063U000e0074U000e007f',rating:73}, {name:'Czech Republic',flag:'🇨🇿',rating:74}]},
  {id:'E',name:'Group E',qualified:2,teams:[{name:'Spain',flag:'🇪🇸',rating:84}, {name:'Sweden',flag:'🇸🇪',rating:76}, {name:'Poland',flag:'🇵🇱',rating:76}, {name:'Slovakia',flag:'🇸🇰',rating:71}]},
  {id:'F',name:'Group F',qualified:2,teams:[{name:'Hungary',flag:'🇭🇺',rating:70}, {name:'Portugal',flag:'🇵🇹',rating:84}, {name:'France',flag:'🇫🇷',rating:88}, {name:'Germany',flag:'🇩🇪',rating:82}]},
],
  teams:{
    England:{rating:85,manager:'Gareth Southgate',style:'balanced'},Italy:{rating:87,manager:'Roberto Mancini',style:'attacking'},
    Spain:{rating:84,manager:'Luis Enrique',style:'attacking'},France:{rating:88,manager:'Didier Deschamps',style:'attacking'},
    Belgium:{rating:85,manager:'Roberto Martinez',style:'attacking'},Germany:{rating:82,manager:'Joachim Low',style:'balanced'},
    Denmark:{rating:80,manager:'Kasper Hjulmand',style:'balanced'},Netherlands:{rating:82,manager:'Frank de Boer',style:'attacking'},
    Portugal:{rating:84,manager:'Fernando Santos',style:'balanced'},Croatia:{rating:80,manager:'Zlatko Dalic',style:'balanced'},
    Switzerland:{rating:78,manager:'Vladimir Petkovic',style:'defensive'},Ukraine:{rating:76,manager:'Andriy Shevchenko',style:'balanced'},
    Austria:{rating:75,manager:'Franco Foda',style:'balanced'},Sweden:{rating:76,manager:'Janne Andersson',style:'defensive'},
    'Czech Republic':{rating:74,manager:'Jaroslav Silhavy',style:'defensive'},Scotland:{rating:73,manager:'Steve Clarke',style:'defensive'},
    Wales:{rating:74,manager:'Robert Page',style:'defensive'},Turkey:{rating:73,manager:'Senol Gunes',style:'balanced'},
    Russia:{rating:71,manager:'Stanislav Cherchesov',style:'defensive'},Hungary:{rating:70,manager:'Marco Rossi',style:'defensive'},
    Poland:{rating:76,manager:'Paulo Sousa',style:'balanced'},Slovakia:{rating:71,manager:'Stefan Tarkovic',style:'defensive'},
    Finland:{rating:69,manager:'Markku Kanerva',style:'defensive'},'North Macedonia':{rating:67,manager:'Igor Angelovski',style:'defensive'},
  },
  allFixtures:[
    {id:'e20_G1',home:'England',away:'Croatia',group:'D',stage:'group',date:'2021-06-13',neutral:false,historicResult:{home:1,away:0}},
    {id:'e20_G2',home:'Scotland',away:'Czech Republic',group:'D',stage:'group',date:'2021-06-14',neutral:true,historicResult:{home:0,away:2}},
    {id:'e20_G3',home:'England',away:'Scotland',group:'D',stage:'group',date:'2021-06-18',neutral:false,historicResult:{home:0,away:0}},
    {id:'e20_G4',home:'Croatia',away:'Czech Republic',group:'D',stage:'group',date:'2021-06-18',neutral:true,historicResult:{home:1,away:1}},
    {id:'e20_G5',home:'Czech Republic',away:'England',group:'D',stage:'group',date:'2021-06-22',neutral:true,historicResult:{home:0,away:1}},
    {id:'e20_G6',home:'Croatia',away:'Scotland',group:'D',stage:'group',date:'2021-06-22',neutral:true,historicResult:{home:3,away:1}},
    {id:'e20_R1',home:'D_1',away:'best3rd',stage:'r16',date:'2021-06-26',neutral:false},
    {id:'e20_R2',home:'D_2',away:'E_2',stage:'r16',date:'2021-06-29',neutral:false},
    {id:'e20_QF1',home:'e20_R1_W',away:'e20_R4_W',stage:'qf',date:'2021-07-03',neutral:false},
    {id:'e20_SF1',home:'e20_QF1_W',away:'e20_QF2_W',stage:'sf',date:'2021-07-07',neutral:false},
    {id:'e20_F',home:'e20_SF1_W',away:'e20_SF2_W',stage:'final',date:'2021-07-11',neutral:false},
  ],
  knockoutStructure:{r16:[{fixtureId:'e20_R1'},{fixtureId:'e20_R2'}],qf:[{fixtureId:'e20_QF1'}],sf:[{fixtureId:'e20_SF1'}],final:{fixtureId:'e20_F'}},
  squads:{
    England:['Harry Kane','Raheem Sterling','Bukayo Saka','Phil Foden','Jack Grealish','Jordan Henderson','Declan Rice','Kalvin Phillips','Kieran Trippier','Luke Shaw','Harry Maguire','John Stones','Jordan Pickford','Marcus Rashford','Jadon Sancho','Mason Mount','Jude Bellingham','Ben Chilwell','Reece James','Tyrone Mings','Aaron Ramsdale','Sam Johnstone'],
    Italy:['Gianluigi Donnarumma','Leonardo Bonucci','Giorgio Chiellini','Marco Verratti','Jorginho','Lorenzo Insigne'],
    Spain:["Alvaro Morata","Pedri","Koke","Sergio Busquets","Jordi Alba"],
    France:["Kylian Mbappe","Karim Benzema","Antoine Griezmann","Paul Pogba","N'Golo Kante"],
  },
  commentary:{context:["The delayed Euro. Played in 2021. Wembley hosts semi and final."],groupStage:["Croatia first — payback for 2018.","Scotland derby at Wembley."],goodResult:["Sterling the hero again."],badResult:["Too cautious. We need to attack."]},
  historicalNotes:{groupResult:'Won Group D — Croatia 1-0, Scotland 0-0, Czech Republic 1-0',knockoutRun:'Beat Germany 2-0, Ukraine 4-0, Denmark 2-1 AET; lost to Italy on penalties in final',topScorer:'Harry Kane 4 goals',keyMoment:"Wembley roars. Saka's penalty saved by Donnarumma. Heartbreak."},
};