window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['brazil14']={
  key:'brazil14',name:'FIFA World Cup',fullName:'2014 FIFA World Cup',
  year:2014,host:'Brazil',startDate:'2014-06-12',endDate:'2014-07-13',
  tagline:"One of England's worst World Cup exits. Beaten by Uruguay and Italy, out in the group stage.",
  qualifyingRequired:true,qualifierGroup:'WCQ_2014_H',format:'world_cup_32',
  colours:{primary:'#009C3B',secondary:'#FEDF00',accent:'#002776',text:'#fff',bg:'#000A00',bgCard:'#001500'},
  atmosphere:{context:"Roy Hodgson's England are at a World Cup in Brazil. Suarez and Balotelli await. Rooney must deliver. Can Gerrard and Lampard finally co-exist?",pressureLevel:'high',mediaExpectation:'Quarter-finals.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'Brazil',flag:'🇧🇷',rating:87}, {name:'Croatia',flag:'🇭🇷',rating:78}, {name:'Mexico',flag:'🇲🇽',rating:77}, {name:'Cameroon',flag:'🇨🇲',rating:70}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'Spain',flag:'🇪🇸',rating:85}, {name:'Netherlands',flag:'🇳🇱',rating:85}, {name:'Chile',flag:'🇨🇱',rating:79}, {name:'Australia',flag:'🇦🇺',rating:70}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'Colombia',flag:'🇨🇴',rating:83}, {name:'Greece',flag:'🇬🇷',rating:72}, {name:'Ivory Coast',flag:'🇨🇮',rating:76}, {name:'Japan',flag:'🇯🇵',rating:72}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'Uruguay',flag:'🇺🇾',rating:82}, {name:'Costa Rica',flag:'🇨🇷',rating:75}, {name:'England',flag:'🏴U000e0067U000e0062U000e0065U000e006eU000e0067U000e007f',rating:81}, {name:'Italy',flag:'🇮🇹',rating:82}]},
  {id:'E',name:'Group E',qualified:2,teams:[{name:'Switzerland',flag:'🇨🇭',rating:78}, {name:'Ecuador',flag:'🇪🇨',rating:73}, {name:'France',flag:'🇫🇷',rating:84}, {name:'Honduras',flag:'🇭🇳',rating:66}]},
  {id:'F',name:'Group F',qualified:2,teams:[{name:'Argentina',flag:'🇦🇷',rating:88}, {name:'Bosnia-Herzegovina',flag:'🇧🇦',rating:73}, {name:'Iran',flag:'🇮🇷',rating:69}, {name:'Nigeria',flag:'🇳🇬',rating:74}]},
  {id:'G',name:'Group G',qualified:2,teams:[{name:'Germany',flag:'🇩🇪',rating:90}, {name:'Portugal',flag:'🇵🇹',rating:83}, {name:'Ghana',flag:'🇬🇭',rating:72}, {name:'USA',flag:'🇺🇸',rating:73}]},
  {id:'H',name:'Group H',qualified:2,teams:[{name:'Belgium',flag:'🇧🇪',rating:82}, {name:'Algeria',flag:'🇩🇿',rating:73}, {name:'Russia',flag:'🇷🇺',rating:72}, {name:'South Korea',flag:'🇰🇷',rating:71}]},
],
  teams:{
    England:{rating:81,manager:'Roy Hodgson',style:'defensive'},Brazil:{rating:87,manager:'Luiz Felipe Scolari',style:'attacking'},
    Germany:{rating:90,manager:'Joachim Low',style:'balanced'},Argentina:{rating:88,manager:'Alejandro Sabella',style:'balanced'},
    Netherlands:{rating:85,manager:'Louis van Gaal',style:'attacking'},France:{rating:84,manager:'Didier Deschamps',style:'balanced'},
    Colombia:{rating:83,manager:'Jose Pekerman',style:'attacking'},Belgium:{rating:82,manager:'Marc Wilmots',style:'attacking'},
    Uruguay:{rating:82,manager:'Oscar Tabarez',style:'balanced'},Chile:{rating:79,manager:'Jorge Sampaoli',style:'attacking'},
    Italy:{rating:82,manager:'Cesare Prandelli',style:'balanced'},Spain:{rating:85,manager:'Vicente del Bosque',style:'attacking'},
    Switzerland:{rating:78,manager:'Ottmar Hitzfeld',style:'defensive'},Mexico:{rating:77,manager:'Miguel Herrera',style:'balanced'},
    'Costa Rica':{rating:75,manager:'Jorge Luis Pinto',style:'defensive'},Greece:{rating:72,manager:'Fernando Santos',style:'defensive'},
    Portugal:{rating:83,manager:'Paulo Bento',style:'balanced'},Algeria:{rating:73,manager:'Vahid Halilhodzic',style:'balanced'},
    Nigeria:{rating:74,manager:'Stephen Keshi',style:'balanced'},Ecuador:{rating:73,manager:'Reinaldo Rueda',style:'balanced'},
    Croatia:{rating:78,manager:'Niko Kovac',style:'balanced'},Ghana:{rating:72,manager:'James Appiah',style:'balanced'},
    USA:{rating:73,manager:'Jurgen Klinsmann',style:'defensive'},Russia:{rating:72,manager:'Fabio Capello',style:'defensive'},
    'Ivory Coast':{rating:76,manager:'Sabri Lamouchi',style:'balanced'},Japan:{rating:72,manager:'Alberto Zaccheroni',style:'balanced'},
    Honduras:{rating:66,manager:'Luis Fernando Suarez',style:'defensive'},Iran:{rating:69,manager:'Carlos Queiroz',style:'defensive'},
    Cameroon:{rating:70,manager:'Volker Finke',style:'balanced'},'Bosnia-Herzegovina':{rating:73,manager:'Safet Susic',style:'balanced'},
    'South Korea':{rating:71,manager:'Hong Myung-bo',style:'balanced'},Australia:{rating:70,manager:'Ange Postecoglou',style:'balanced'},
  },
  allFixtures:[
    {id:'b14_G1',home:'England',away:'Italy',group:'D',stage:'group',date:'2014-06-14',neutral:true,historicResult:{home:1,away:2}},
    {id:'b14_G2',home:'Uruguay',away:'Costa Rica',group:'D',stage:'group',date:'2014-06-14',neutral:true,historicResult:{home:1,away:3}},
    {id:'b14_G3',home:'England',away:'Uruguay',group:'D',stage:'group',date:'2014-06-19',neutral:true,historicResult:{home:1,away:2}},
    {id:'b14_G4',home:'Italy',away:'Costa Rica',group:'D',stage:'group',date:'2014-06-20',neutral:true,historicResult:{home:0,away:1}},
    {id:'b14_G5',home:'England',away:'Costa Rica',group:'D',stage:'group',date:'2014-06-24',neutral:true,historicResult:{home:0,away:0}},
    {id:'b14_G6',home:'Italy',away:'Uruguay',group:'D',stage:'group',date:'2014-06-24',neutral:true,historicResult:{home:0,away:1}},
    {id:'b14_R1',home:'D_1',away:'C_2',stage:'r16',date:'2014-06-28',neutral:true},
    {id:'b14_QF1',home:'b14_R1_W',away:'b14_R2_W',stage:'qf',date:'2014-07-04',neutral:true},
    {id:'b14_SF1',home:'b14_QF1_W',away:'b14_QF2_W',stage:'sf',date:'2014-07-08',neutral:true},
    {id:'b14_3P',home:'b14_SF1_L',away:'b14_SF2_L',stage:'3rd',date:'2014-07-12',neutral:true},
    {id:'b14_F',home:'b14_SF1_W',away:'b14_SF2_W',stage:'final',date:'2014-07-13',neutral:true},
  ],
  knockoutStructure:{r16:[{fixtureId:'b14_R1'}],qf:[{fixtureId:'b14_QF1'}],sf:[{fixtureId:'b14_SF1'}],final:{fixtureId:'b14_F'}},
  squads:{
    England:['Wayne Rooney','Steven Gerrard','Frank Lampard','Joe Hart','Gary Cahill','Phil Jagielka','Glen Johnson','Leighton Baines','Jordan Henderson','Jack Wilshere','Raheem Sterling','Daniel Sturridge','Danny Welbeck','Ross Barkley','Adam Lallana','Luke Shaw','Phil Jones','Chris Smalling','Rickie Lambert','Tom Cleverley','Fraser Forster','Ben Foster'],
    Germany:["Thomas Muller","Miroslav Klose","Mesut Ozil","Toni Kroos","Philipp Lahm","Manuel Neuer"],
    Argentina:["Lionel Messi","Gonzalo Higuain","Angel Di Maria","Sergio Romero"],
    Brazil:["Neymar","Oscar","David Luiz","Julio Cesar"],
  },
  commentary:{context:["The group of death. Italy and Uruguay await. Hodgson under pressure."],groupStage:["Italy first — Pirlo is the danger.","Uruguay: Suarez. Be warned."],goodResult:["Rooney looks sharp."],badResult:["Gerrard and Lampard still can't play together."]},
  historicalNotes:{groupResult:'3rd in Group D — lost Italy 1-2, lost Uruguay 1-2 (Suarez biting incident), drew Costa Rica 0-0',knockoutRun:'Eliminated in group stage',topScorer:'Steven Gerrard 1 goal',keyMoment:"Suarez bites Chiellini. Gerrard's slip that didn't happen here — but England still went out."},
};