window.TOURNAMENTS=window.TOURNAMENTS||{};
window.TOURNAMENTS['euro2012']={
  key:'euro2012',name:'UEFA European Championship',fullName:'UEFA Euro 2012',
  year:2012,host:'Poland & Ukraine',startDate:'2012-06-08',endDate:'2012-07-01',
  tagline:"Hodgson's England. Rooney suspended. Ashley Young's diving. Penalties vs Italy.",
  qualifyingRequired:true,qualifierGroup:'ECQ_EURO2012_G',format:'euros_16',
  colours:{primary:'#D4213D',secondary:'#1A3A5C',accent:'#FFFFFF',text:'#fff',bg:'#00000A',bgCard:'#00000F'},
  atmosphere:{context:"Roy Hodgson replaces Capello. Rooney misses the first two games suspended. England grind through the group and lose to Italy on penalties.",pressureLevel:'medium',mediaExpectation:'Quarter-finals.'},
  groups:[
  {id:'A',name:'Group A',qualified:2,teams:[{name:'Poland',flag:'🇵🇱',rating:74}, {name:'Greece',flag:'🇬🇷',rating:73}, {name:'Russia',flag:'🇷🇺',rating:76}, {name:'Czech Republic',flag:'🇨🇿',rating:78}]},
  {id:'B',name:'Group B',qualified:2,teams:[{name:'Netherlands',flag:'🇳🇱',rating:85}, {name:'Denmark',flag:'🇩🇰',rating:76}, {name:'Germany',flag:'🇩🇪',rating:88}, {name:'Portugal',flag:'🇵🇹',rating:83}]},
  {id:'C',name:'Group C',qualified:2,teams:[{name:'Spain',flag:'🇪🇸',rating:92}, {name:'Italy',flag:'🇮🇹',rating:85}, {name:'Republic of Ireland',flag:'🇮🇪',rating:70}, {name:'Croatia',flag:'🇭🇷',rating:79}]},
  {id:'D',name:'Group D',qualified:2,teams:[{name:'England',flag:'🏴U000e0067U000e0062U000e0065U000e006eU000e0067U000e007f',rating:81}, {name:'France',flag:'🇫🇷',rating:82}, {name:'Ukraine',flag:'🇺🇦',rating:74}, {name:'Sweden',flag:'🇸🇪',rating:76}]},
],
  teams:{
    England:{rating:81,manager:'Roy Hodgson',style:'defensive'},Spain:{rating:92,manager:'Vicente del Bosque',style:'attacking'},
    Germany:{rating:88,manager:'Joachim Low',style:'balanced'},Italy:{rating:85,manager:'Cesare Prandelli',style:'attacking'},
    Portugal:{rating:83,manager:'Paulo Bento',style:'balanced'},France:{rating:82,manager:'Laurent Blanc',style:'balanced'},
    'Czech Republic':{rating:78,manager:'Michal Bilek',style:'balanced'},Ukraine:{rating:74,manager:'Oleg Blokhin',style:'balanced'},
    Croatia:{rating:79,manager:'Slaven Bilic',style:'balanced'},Denmark:{rating:76,manager:'Morten Olsen',style:'defensive'},
    Russia:{rating:76,manager:'Dick Advocaat',style:'balanced'},Greece:{rating:73,manager:'Fernando Santos',style:'defensive'},
    Netherlands:{rating:85,manager:'Bert van Marwijk',style:'attacking'},Sweden:{rating:76,manager:'Erik Hamren',style:'defensive'},
    'Republic of Ireland':{rating:70,manager:'Giovanni Trapattoni',style:'defensive'},Poland:{rating:74,manager:'Franciszek Smuda',style:'balanced'},
  },
  allFixtures:[
    {id:'e12_G1',home:'England',away:'France',group:'D',stage:'group',date:'2012-06-11',neutral:true,historicResult:{home:1,away:1}},
    {id:'e12_G2',home:'Ukraine',away:'Sweden',group:'D',stage:'group',date:'2012-06-11',neutral:true,historicResult:{home:2,away:1}},
    {id:'e12_G3',home:'England',away:'Ukraine',group:'D',stage:'group',date:'2012-06-15',neutral:true,historicResult:{home:1,away:0}},
    {id:'e12_G4',home:'France',away:'Sweden',group:'D',stage:'group',date:'2012-06-15',neutral:true,historicResult:{home:2,away:0}},
    {id:'e12_G5',home:'England',away:'Sweden',group:'D',stage:'group',date:'2012-06-15',neutral:true,historicResult:{home:3,away:2}},
    {id:'e12_G6',home:'Ukraine',away:'France',group:'D',stage:'group',date:'2012-06-15',neutral:true,historicResult:{home:0,away:2}},
    {id:'e12_QF1',home:'ENG_OF_D',away:'C_2',stage:'qf',date:'2012-06-24',neutral:true,historicResult:{home:0,away:0}},
    {id:'e12_SF1',home:'e12_QF1_W',away:'e12_QF2_W',stage:'sf',date:'2012-06-27',neutral:true},
    {id:'e12_F',home:'e12_SF1_W',away:'e12_SF2_W',stage:'final',date:'2012-07-01',neutral:true},
  ],
  knockoutStructure:{qf:[{fixtureId:'e12_QF1'}],sf:[{fixtureId:'e12_SF1'}],final:{fixtureId:'e12_F'}},
  squads:{
    England:['Wayne Rooney','Ashley Young','Frank Lampard','Steven Gerrard','Joe Hart','John Terry','Rio Ferdinand','Ashley Cole','Glen Johnson','Kyle Walker','Danny Welbeck','Stewart Downing','James Milner','Scott Parker','Gary Cahill','Phil Jones','Theo Walcott','Joleon Lescott','Andy Carroll','Alex Oxlade-Chamberlain','Jack Wilshere','Daniel Sturridge'],
    Spain:["Andres Iniesta","Xavi","Fernando Torres","David Silva","Cesc Fabregas","Iker Casillas"],
    Germany:["Mario Gomez","Mesut Ozil","Thomas Muller","Manuel Neuer","Sami Khedira"],
    Italy:["Mario Balotelli","Andrea Pirlo","Antonio Cassano","Gianluigi Buffon"],
  },
  commentary:{context:["Hodgson's first tournament. Rooney suspended for first two."],groupStage:["France first — must not lose.","Ukraine: must win."],goodResult:["Rooney back and looking sharp."],badResult:["Too defensive. Not enough creativity."]},
  historicalNotes:{groupResult:'1st in Group D — drew France 1-1, beat Ukraine 1-0, beat Sweden 3-2',knockoutRun:'Lost to Italy on penalties in QF',topScorer:'Rooney 1 goal',keyMoment:"Gerrard's first-half header. Balotelli destroys Germany in SF. England lose 2-4 on pens to Italy."},
};